### ISSUE TITLE
Add by Object URL - Hint not showing up

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#1033]
## What package are you referring to?

Frontend

## Describe the bug

When hovering over the cube icon (next to the close icon) we do not show up a hint. Users don't know what that cube means :) We're open to either converting that into an actual small text button, or just adding a simple v-hint. 

![image](https://user-images.githubusercontent.com/7696515/192318711-e127fe23-1146-4230-8bb2-fb0f1c3abddd.png)

**Comment by BajajAyush** [comment]
hey, please assign it to me. I think I can fix this.

**Comment by didimitrie** [comment]
@BajajAyush, apologies for the late reply! This seems to have been fixed actually ages ago, and we mistakenly added the `hacktoberfest` label... I'll close the issue now to stop causing confusion! 

<img width="806" alt="image" src="https://user-images.githubusercontent.com/7696515/194826878-80e6c67c-278b-454d-9c27-d888d94bd2b5.png">

**Comment by BajajAyush** [comment]
Okay, no problem @didimitrie
