### ISSUE TITLE
Scrolling element properties on mobile does not work

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#1034]
## What package are you referring to?

Frontend 

## To Reproduce

Select an object in the viewer on your mobile phone and expand a few properties. If your screen size it's small enough - it will be! - you won't be able to scroll the panel.

https://user-images.githubusercontent.com/7696515/192319808-73598b86-35fe-498b-8ade-c14f24192a29.mov

**Comment by nooras** [comment]
Hi can i work on this ?

**Comment by nooras** [comment]
HI @didimitrie @jsdbroughton 
I am not able to start server and currently have lots of issue with my system. So un-assigning myself.
