### ISSUE TITLE
Viewer: Selection Performance Improvements

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#1049]
Because we're batching objects aggressively, for some streams we end up with large batches. Three.js does not accelerate ray-triangle intersections involved in picking at all. So that's why for large batches there are a lot of triangles churned each time there is an intersection test. We can resolve this in two ways:
- Test the picking rays against the individual object bounding boxes (which three doesn't know about, but they exist), then use the geometry range for each successful hit, instead of the whole geometry batch for ray-triangle testing. This basically brings the performance to three's default
- Introduce an acceleration structure (BVH, K-D Tree) and use that to (greatly) improve ray-* testing. Additionally, this would be useful for other features well

**Comment by AlexandruPopovici** [comment]
Draft integration of the `three-mesh-bvh` library handles this issue. Details [here](https://www.notion.so/speckle/BVH-303530ab75314456842fa4a3dd55cacc#22cc93ca83714bf5b6974ab831bcaa63)
