### ISSUE TITLE
Limit maximum batch size

### ISSUE THREAD

**Issue by AlexandruPopovici** [specklesystems/speckle-server#1051]
We need to limit the maximum batch size. On chromium for example, for extra-large batches I think we're seeing scene-splits which is bad.

**Comment by gjedlicska** [comment]
Is this about batches inside the viewer, or the batch size, how stream data is received from the backend?

**Comment by AlexandruPopovici** [comment]
It's about the geometry batches inside the viewer. Currently there is not size limit, so for streams with dense geometries and little to no material variation we end up with batches so large that the driver is forced to do scene splits. This is bad for performance
