### ISSUE TITLE
Compute near and far camera clipping planes dynamically

### ISSUE THREAD

**Issue by AlexandruPopovici** [specklesystems/speckle-server#1067]

**Comment by fraguada** [comment]
Objects modeled with "small" units, for example a sphere with radius 9, are clipped in the viewer. If the same objects are modeled with larger units, say 100 radius sphere, the objects are visible. 

Here is a stream that displays this issue:
https://speckle.xyz/streams/b85d53c3b4

First commits are of the small sphere, the latest is of a larger one.

**Comment by jsdbroughton** [comment]
Stream sent from QGIS, arguably large objects but with a custom CRS and alternative GIS projection which makes it large objects possibly a long way away.

https://latest.speckle.dev/streams/e9285828d7/commits/9b80b7a70c

That commit is problematic.

**Comment by AlexandruPopovici** [comment]
Migrated to Jira
