### ISSUE TITLE
Web viewer rendering glitchy or missing curves

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-server#107]
Test stream: https://staging.speckle.dev/streams/76ad4bd698

![image](https://user-images.githubusercontent.com/16748799/108862403-192a5800-75e8-11eb-872f-f852cd201f10.png)

Sent curves:

![image](https://user-images.githubusercontent.com/16748799/108862309-044dc480-75e8-11eb-859f-a1c88b3306d1.png)

**Comment by AlanRynne** [comment]
I think we forgot to close this. It was fixed in #109, unless anyone int he team found some non-working edge case, should we close?
