### ISSUE TITLE
Papercut: no empty state in the commits page

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#1070]
The Commits page does not have an empty state and keeps showing a loading bar if there are no commits.

NOTE: I don't think the user can reach this page from the frontend, so it's not a big deal - feel free to close this if irrelevant.

Sample page: https://latest.speckle.dev/streams/7c9c7a7bd6/commits/

![no-commits](https://user-images.githubusercontent.com/2679513/193650861-78e4daca-3ebe-41cf-a984-274be7bd225e.gif)

**Comment by didimitrie** [comment]
Hehe, I got this when url hacking/copy pasting too several times so far - and each time, after a mini heart-attack that stuff is broken, i decided not to make it an issue because it's not user reachable. Given pending revamp of these parts, i'll close to help with focus :)
