### ISSUE TITLE
Web viewer load cancellation

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#108]
The viewer keeps loading "stale" data even if you've moved away from the page displaying it.

**Comment by didimitrie** [comment]
depends on #131 and #132; moving backlog

**Comment by cristi8** [comment]
When generating previews for very large objects, if the stream exceeds a threshold of browser memory usage, we should automatically cancel the loading and screenshot what we have until then.

This allows Speckle to not have a hard limit on stream size and the PreviewService to work within some defined memory requirements and limits ("best effort" for large streams)
