### ISSUE TITLE
Expanding some fields on the viewer sidebar freezes the tab:

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-server#1094]
From this commit: https://speckle.xyz/streams/f0532359ac/commits/98678e2a3d

When expanding the `@blocks` property on the commit object, the whole tab freezes as if it were waiting for something to load, but in my case it never came back... 🥶

This can be reproduced also with the `__closure` property in that same commit, but in that case it does come back after several seconds frozen.

@didimitrie said something on discord about this being possibly caused by our _"eager hover effect"_, which I guess @fabis94 or @AlexandruPopovici would know what it means 😅

Dim's note: this needs investigation - i suspect it's to do with the frontend telling the viewer to highlight a lot of objects at once, but unsure! 

![2022-10-10 09 30 39](https://user-images.githubusercontent.com/2316535/194820854-d6751b07-b5de-42c7-acf0-5eb8bd87c1ea.gif)

**Comment by fabis94** [comment]
As discussed with Dim, this is more of a @speckle/viewer issue than a @speckle/frontend issue, so it will have to be look at and optimized by Dim or Alex. Moving back to Backlog!

**Comment by AlexandruPopovici** [comment]
@fabis94  @didimitrie  Cool, I'll have a look. Did you guys find out what frontend operation is making the viewer hang?

**Comment by fabis94** [comment]
@AlexandruPopovici It's FilteringManager:highlightObjects(), it triggers a lot of walking in three.js (Dim will know more)

**Comment by AlexandruPopovici** [comment]
Addressed here: https://github.com/specklesystems/speckle-server/pull/1133
Filtering can still be slow in very dense streams, but speeding it up further will require a more general solution
