### ISSUE TITLE
Ignore clipping box in AO calcs

### ISSUE THREAD

**Issue by fraguada** [specklesystems/speckle-server#1110]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Viewer

## Describe the bug

It seems the clipping box is participating in AO calcs and some nice artifacts are appearing.

## To Reproduce

Use clipping box and clip away!

## Expected behavior

Clipping box should not be taken into consideration when calc'ing AO

## Screenshots

<img width="840" alt="Screenshot 2022-10-13 at 13 16 29" src="https://user-images.githubusercontent.com/1014562/195584438-e75fec52-6b1c-454c-9938-d2c2d822ff24.png">
<img width="898" alt="Screenshot 2022-10-13 at 13 18 18" src="https://user-images.githubusercontent.com/1014562/195584466-6d6d9ba7-fa69-4ba5-a676-17a2b6d82c80.png">

![viewer-clippingbox](https://user-images.githubusercontent.com/1014562/195584747-481c9e44-e0d0-48e7-bb30-2d8caea3ae1d.gif)

## System Info

If applicable, please fill in the below details - they help a lot!

### Desktop (please complete the following information):

- OS: macOS 12.2.1
- Browser: firefox
- Version: 105.0.3 64bit

**Comment by AlexandruPopovici** [comment]
Fixed this issue on top of this PR: https://github.com/specklesystems/speckle-server/pull/1156 since this is where the new rendering pipeline is which is not compatible with the older one
