### ISSUE TITLE
Make it clearer to understand who has access to do batch commit actions

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-server#1114]
## Description

Can’t see selectbox on streams where i am not the owner (contributor, reviewer). But as a user, i was (for some reason) expecting to see it.

## Expected Behaviour

Seeing the checkbox.

## Steps to reproduce

1. Go to any stream you are not the owner of
2. Try to select multiple commits

## Streams/Commits Used

[https://latest.speckle.dev/streams/8e2e6ad4f3/branches/main](https://latest.speckle.dev/streams/8e2e6ad4f3/branches/main)

## Screenshots

![image](https://user-images.githubusercontent.com/51519350/195623894-18e70ea2-2d0c-4794-a0c1-d98263fea94a.png)

**Comment by fabis94** [comment]
This will probably involve adding a greyed out checkbox with a tooltip
