### ISSUE TITLE
Frontend App Scaffolding

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#1119]
Initial requirements:
- vue 3
- nuxt, for nice SSR capabilities & a framework's guide rails
- tailwind, to stop fighting UI frameworks
- storybook, to be proper & be able to evolve a proper design system

Other decisions and requirements, up to @fabis94 (ie, relay vs apollo)

**Comment by fabis94** [comment]
All of this is set up in branch `frontend-2`
