### ISSUE TITLE
Unspecified behaviour on ctrl-click objects leading to odd visual effects

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-server#1136]
## What package are you referring to?

Viewer

## Describe the bug

Control-Clicking an object in the viewer variably causes the object to change appearance in the display. 
I have seen objects: Invert colour, disappear, and appear with outlines.

These effects are sometimes cleared on the next interaction, either object selection, deselection, model rotation or window resize.

Clearing the visual effects is as inconsistent as their appearance.

## Context

Is control-clicking a planned behaviour? What is it intended to achieve?

I have only check for this on one of the QGIS shape and polyline streams: https://speckle.xyz/streams/17b0b76d13/commits/54f5ef6932

## Screenshots
![Screen Recording 2022-10-21 at 17 14 08 2022-10-21 18_52_01](https://user-images.githubusercontent.com/760691/197258428-a849f069-d110-42ee-9e2f-148edd82c5c2.gif)

## System Info

If applicable, please fill in the below details - they help a lot!

### Desktop (please complete the following information):

- OS: macOS 12.6
- Browser: Chrome: Brave
- Version 106

**Comment by AlexandruPopovici** [comment]
Ctrl+click is a left over debug feature I needed at some point. It selects the entire batch the object you click belongs to. I'll remove it from production.
