### ISSUE TITLE
Bug: stream_delete webhook didn't work

### ISSUE THREAD

**Issue by Zhuangkh** [specklesystems/speckle-server#1141]
## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Backend

## Describe the bug

Hi, I am developing a notification bot for Microsoft Teams using speckle-server's webhook.
I found that the `stream_delete` event didn't work everytimes and it's difficult to locate the conditions for the reproduce. Any ideas?

**Comment by didimitrie** [comment]
Hi @Zhuangkh! Thanks for reporting this, and sorry we're getting back late. 

It's weird event to actually capture and send out, namely because you need to subscribe to the resource (stream) that then gets deleted. 

Can you reproduce using https://webhook.site? I've succesfully received the event:

![image](https://user-images.githubusercontent.com/7696515/198892962-bf567406-ee6c-404e-bb3c-f3c34570d4b3.png)

**Comment by Zhuangkh** [comment]
Hi @didimitrie 
The weird thing is that it doesn't always fail. I also did a test on https://webhook.site, this video is a failed attempt.

https://user-images.githubusercontent.com/30818313/199384379-18ae4d86-7e07-43c5-8b10-fc7e5a1a945f.mp4

**Comment by Zhuangkh** [comment]
Hi @didimitrie 
The weird thing is that it doesn't always fail. I also did a test on https://webhook.site, this video is a failed attempt.

https://user-images.githubusercontent.com/30818313/199384379-18ae4d86-7e07-43c5-8b10-fc7e5a1a945f.mp4

**Comment by didimitrie** [comment]
Gotcha. I think I've managed to reproduce this on my end using `speckle.xyz`. Tried various combinations, and like you said - sometimes it works, sometimes it doesn't. 

What I've tried: 
- wh triggered only by `stream_delete` -> mostly didn't work
- wh triggered by `stream_delete` and `stream_edit` -> `stream_edit` works, half of the times `stream_delete` did too
- etc. 

It's a legitimate bug, and we'll look into it!

**Comment by gjedlicska** [comment]
I think i've found the cause of the issue [here](https://github.com/specklesystems/speckle-server/blob/main/packages/server/modules/webhooks/migrations/20210701180000-webhooks.js#L7).

The rows in webhook events are deleted as the streamId deletion cascades in the DB. 
The webhook events table is used as a task queue for the webhook service.
There are times, when we get lucky, and the [tick](https://github.com/specklesystems/speckle-server/blob/main/packages/webhook-service/src/main.js#L113) fires at just the right time.

A short term solution could be to remove the foreign key constraint from the `webhooks_events` table to `stream.id`.
This would cause a buildup of event rows in the table in the long run.

**Comment by didimitrie** [comment]
Okay, so it's a more complicated fix. I think the only way is to remove the cascade. Could we deal with the buildup with a cron job, since you've got it running for the digest emails? ie, run a cleanup query every now and then...
 
((I'm interested in this as there could be other potential uses for db cleanup scripts in the future))

**Comment by gjedlicska** [comment]
We can, I've made the [taskScheduler](https://github.com/specklesystems/speckle-server/blob/main/packages/server/modules/core/services/taskScheduler.ts) as part of server core. So it is reusable to trigger arbitrary callbacks.

We can do `on delete set null` and clean the rows periodically, where the streamId is null.

**Comment by gjedlicska** [comment]
I retract that a bit, we cannot set the `streamId` column to null. We need to drop the FK constraint. If the `streamId` is set to null, on stream delete, the right event event configs cannot be found, when dispatching the webhook events.

This changes the cleanup logic only, where we clean the webhook configs, where their streamId is pointing to a non existent stream.
