### ISSUE TITLE
ortho mode in viewer

### ISSUE THREAD

**Issue by thoffeller** [specklesystems/speckle-server#1177]
Hi specklers,
currently the viewer is in perspective mode only. So, when zooming close to objects, the clipping planes hide objects.
In many situations a perspective representation isn't the best way to inpect models. So, an ortho camera would be very helpful.

## Prerequisites

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [ ] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x ] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [ ] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [ ] I'm requesting the feature to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

Viewer

## Is your feature request related to a problem? Please describe.

objects are hidden in perspective mode

## Describe the solution you'd like

add an ortho camera mode ( button in the toolbar) for switching between perspective and ortho representation

## Describe alternatives you've considered

There are no alternatives ;-)

## Related issues or community discussions

Haven't found one with this topic.

**Comment by AlexandruPopovici** [comment]
This issue has been resolved in [this PR](https://github.com/specklesystems/speckle-server/pull/1235)
