### ISSUE TITLE
Proposal:  add concept of `stream creator`

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#120]
Currently, if a user creates a stream and adds other users as owners it's not possible to know who originally created that stream.
While this is not fundamental information it'd be nice and it would help collaborative aspects.

Partly related to: https://github.com/specklesystems/speckle-server/issues/118

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.
