### ISSUE TITLE
Scroll disabled for object properties

### ISSUE THREAD

**Issue by KatKatKateryna** [specklesystems/speckle-server#1218]
Mouse wheel or slider click doesn't scroll the list of object properties. Dragging/clicking the slider just rotates the model. 
Windows + Chrome

![image](https://user-images.githubusercontent.com/89912278/203076146-dd263524-026a-45be-910f-d494d92e2573.png)

To reproduce:
https://latest.speckle.dev/streams/16d73b756a/commits/2f8cfa8644

**Comment by jsdbroughton** [comment]
In a touch environment, action bubbles down to interact with the 3d viewer. Same issue.

**Comment by ahofbeck** [comment]
it seems this issue is happening on Edge and Chrome but not on Firefox.

**Comment by ChristopherConnock** [comment]
- scrolls with mouse wheel on Firefox, but not scrollbar (which shows as native in Firefox).
- does not scroll on Chrome with wheel or scrollbar.

Don't know if this should be a separate issue, but the properties bleed off the bottom of the screen even when scrolling is enabled.
