### ISSUE TITLE
Remove artificial limit on branch name character count in frontend

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-server#125]
### Expected vs. Actual Behavior

The branch editing dialog in the frontend has an artificial length limit of 25 characters. Branches with names longer than this can be created outside of the frontend. This limit should be removed as I don't see it serving a purpose.

![image](https://user-images.githubusercontent.com/7717434/110516901-1197a280-8102-11eb-9d2d-3d519ce497a1.png)

eg the branch above (42 characters) already has this name, but I can't edit it from the frontend because of this 25 character cap

### Reproduction Steps & System Config (win, osx, web, etc.)

Create a branch on a stream with a connector or with an SDK, then try editing it in the frontend

**Comment by teocomi** [comment]
We decided to limit it to 100chars, and add limits in the frontend and desktop ui.
