### ISSUE TITLE
Viewer Filter's Performance and Bug

### ISSUE THREAD

**Issue by sanchez** [specklesystems/speckle-server#1272]
Upon enabling a Filter against approximately 300 objects the viewer begins to dramatically slow down, additionally if I do the following steps then the coloring of the filter is no longer accurate:

1. Set a filter
2. Remove filter
3. Set a different filter

Example project: https://speckle.xyz/streams/f95d8deb90/commits/30f31becb6
Set a filter for `EmbodiedCarbon`, then set a new filter for `Floor`. You will notice the object closest to the ground is a pinker color than the objects higher up, however it has a floor value of 0, it should be the bluest blue.

## Screenshots
Floor filter enabled:
![image](https://user-images.githubusercontent.com/5264697/207792624-59975fba-4f6c-462e-87d9-045bfd3fb357.png)

Properties of the floor:
![image](https://user-images.githubusercontent.com/5264697/207792729-a5d73dbc-31b3-4748-95cd-8a3afe53015a.png)

I am using Speckle v2.11.2 in Firefox.

Cheers.

## Prerequisites
- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?
Not sure, I would guess viewer

### Desktop (please complete the following information):

- OS: Windows
- Browser: Firefox
- Version: v2.11.2

**Comment by AlexandruPopovici** [comment]
Hi @sanchez 

Thanks for reporting this. The issues were a very good catch!
We have resolved them and the fixes will soon be available on `latest` and later on in the next release

Cheers
