### ISSUE TITLE
Unable to pass multiple groups to ```setUserObjectColors```

### ISSUE THREAD

**Issue by gouldingken** [specklesystems/speckle-server#1290]
It's unclear if this is a bug or documentation issue (or user error), but I'm having trouble using the ```setUserObjectColors``` method:

```setUserObjectColors(groups: [{ objectIds: string[]; color: string }])```

I'm not familiar with that TS syntax. If this is an array of objects that contain objectIds and a color, should that not be written as follows?:

```groups: { objectIds: string[]; color: string }[]```

The TS error I'm getting when I try to pass more than 1 element through is: 

```
TS2345: Argument of type '[{ objectIds: string[]; color: string; }, { objectIds: string[]; color: string; }]' is not assignable to parameter of type '[{ objectIds: string[]; color: string; }]'.   Source has 2 element(s) but target allows only 1.
```

I've tried using the exact code specified in https://github.com/specklesystems/speckle-server/pull/1205 - but got the error above.

**Comment by AlexandruPopovici** [comment]
Hi @gouldingken 

`setUserObjectColors` takes a single parameter which needs to be **an array**. 
Each element of that array needs to be of type: 
```
{
  objectIds: string[]
  color: string
}
```
The `groups` parameter is an array, because this way you can provide multiple user colors to groups of ids in a single call. If you want to set a user color to a single group of ids, you can call it with a single element array like so:

```
setUserObjectColors([
  {
    objectIds: [
      'id1',
      'id2',
      'id3',
      'id4'
    ],
    color: '#8b5cf6'
  }
])
```

**Comment by gouldingken** [comment]
That works. But it still throws the TypeScript error. I think you just need to fix the type syntax.

**Comment by AlexandruPopovici** [comment]
From the error you are getting in you initial comment:
`[{ objectIds: string[]; color: string; }, { objectIds: string[]; color: string; }]`

The type you are trying to assign is incorrect and it's not what `setUserObjectColors` expects as it's argument type. The error message explains what is wrong accurately

**Comment by gouldingken** [comment]
I have the code working fine. I just have to disable the type checking. 

I'm pretty sure it's just that the first '[' needs to come after the object type, not before.

If this were exciting an array of numbers, you'd write it as number[], not [number], right?

**Comment by didimitrie** [comment]
This might becoming a typescript lesson for all of us (especially me!) I think i wrote that function (?) and my intention was `pass in a non-empty array` not `pass in an array of one object`. I'm happy to defer to whatever signature is needed there, and we can also skip the non-empty array part; ie it can be just `{ objectIds: string[]; color: string; }[]` - if i got my typescript right :D
