### ISSUE TITLE
bug(viewer): Opening a comment causes weird artifact in the viewer

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-server#1291]
## Description

When I open the added comment in the following commit and close it, I get a weird artifact in the viewer. See attached image. 

## Commit

https://latest.speckle.dev/streams/e8b81c24f5/commits/4d81103fbd

## Workaround

Activating sections and deactivating again gets rid of it (thanks @jsdbroughton for finding this)

## Screenshots

![opera_soKYsiLzwU](https://user-images.githubusercontent.com/51519350/211270383-b675bdfc-0c38-4182-b6e0-ccde13970b7d.png)

**Comment by AlexandruPopovici** [comment]
Cannot replicate anymore in FE2 + viewer API 2.0
