### ISSUE TITLE
Remove double encoding of webhook payloads

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-server#1292]
# WARNING

this is a (small) breaking change to the way the webhook payload is structured, but its for the better.

Currently the webhook payload is a string encoded json value, so every webhook receiver needs to double decode json to get the payload.

**Comment by AlanRynne** [comment]
I upvote this haha haven't done webhook stuff for a while but I remember this stood out as a weird to me :)

**Comment by gjedlicska** [comment]
fixed by #1294
