### ISSUE TITLE
Separate frontend builds from server builds

### ISSUE THREAD

**Issue by cristi8** [specklesystems/speckle-server#131]
Right now, the frontend is built and embedded inside the backend build and served with express.

Ideally, there should be separate builds to allow for more flexible deployments.

**Comment by cristi8** [comment]
I did a quick research and listed 3 options of how we can proceed.

What do you guys think is the current best approach?


### Current situation

Fontend example URLs:

- https://speckle-server-domain/  --> app.html
- https://speckle-server-domain/js/chunk-03765320.58ba1dfb.js  --> js/chunk-03765320.58ba1dfb.js
- https://speckle-server-domain/streams/3073b96e86  --> app.html  (--vue router--> stream page)
- // A lot more custom routes from vue router
- https://speckle-server-domain/NONEXISTENT  --> app.html (--vue router--> NotFound page)


Backend example URLs:

- https://speckle-server-domain/graphql
- https://speckle-server-domain/explorer
- https://speckle-server-domain/auth/pwdreset/request
- https://speckle-server-domain/objects/:streamId/:objectId
- // A lot more custom routes registered by server modules
- https://speckle-server-domain/metrics

Current functionality:

- Server build has a local copy of the frontend build files
- For a request for path X, express app looks first at backend-registered paths, then on existing files in the frontend build, then sends the frontend app.html so the vue router can show the appropiate page.


---

### Possible approaches for increasing separation

#### 1. In a production server app, use the same approach as for development environment:  reverse proxy to a frontend server host:port.

Pros:
 - We can build and deploy the frontend and backend separately

Cons:
 - Frontend requests still have to go through the backend code
 - Delay is introduced, because new connections must be made from the backend to the frontend service.


#### 2. Create an frontend deployment with nginx. And configure nginx with all routes from the backend or the frontend (with regular expressions), and have it reverse proxy the backend requests to the apropiate deployment.

Pros:
 - We can build and deploy the frontend and backend separately
 - Frontend requests don't reach the backend code

Cons:
 - We should keep the routing rules up to date (the nginx config MUST be kept up to date with all changes in frontend or backend routes)


#### 3. [longer-term plan/discussions] Put all backend urls on a different subdomain (https://api.speckle-server-domain/*)

Pros:
 - Frontend requests don't reach the backend
 - Backend requests don't reach the frontend
 - We can deploy the frontend anywhere, without the need to reverse proxy from nginx

Cons:
 - Takes a lot of work to restructure and change things everywhere
 - Windows clients would have to use the backend URL for connecting to a speckle server

**Comment by didimitrie** [comment]
Would a variant of (3), let's call it (4), on the lines of: 

- enforce all backend urls to be `${serverdomain}/api`
  - `${serverdomain}/api/graphql` -> gql server
  - `${serverdomain}/api/auth/etc`-> all other endpoints
- configure nginx accordingly, as in (3) 

This eliminates the biggest con of (3), Windows clients would have to use the backend URL for connecting to a speckle server; no need to update nginx anymore beyond /api vs /root requests; and restructuring things everywhere is still a good hefty task, but doable. 

Watcha thunk?

**Comment by cristi8** [comment]
Yes, sounds good, beyond the backend path restructuring and updates in client libs, things should go very smoothly.

It will however introduce incompatibilities with existing client code that talks to the current endpoints, so maybe we should schedule it for the next (major) release that requires client updates?
