### ISSUE TITLE
Shadow artifact lines on some computers

### ISSUE THREAD

**Issue by gouldingken** [specklesystems/speckle-server#1311]
I'm seeing strange artifacts that seem to be related to the stencil shadows (from sunlight). They disappear when I disable sunlight - and are always perpendicular to the sun angle. 

I have tried the viewer on a number of machines, but only encountered this issue on my own setup. I fear that will make it hard to replicate for you, but wanted to document it here in any case. Hopefully others can weigh in if they see the same issue.

With artifacts:
![image](https://user-images.githubusercontent.com/760010/212149280-888db0de-24e3-4da2-a3bf-a15c993e98df.png)

Same viewer without artifacts:
![image](https://user-images.githubusercontent.com/760010/212149419-ec107930-51d6-4e4f-8a74-359a57785068.png)

**Comment by AlexandruPopovici** [comment]
Hi @gouldingken 

Thanks for pointing this out! We've had the same issue in the past several times, generally on Intel integrated GPUs. Strangely, the issue went away after OS/Browser updates. For further investigations, would you please let us know the following:
- Browser & Browser version
- OS & OS version

We'll also be needing the GPU model, but we'll need more infomration there, so first we need to know on which browser you are getting the artifacts, then we'll be able to provide further instruction on how to get that required information

Cheers

**Comment by AlexandruPopovici** [comment]
This only seems to be happening on intel Iris Xe cards. The solution is to install the intel drivers https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html
