### ISSUE TITLE
Bug: Viewer displays filtered-out invisible elements as "ghosted" - only hides when unfiltered

### ISSUE THREAD

**Issue by gouldingken** [specklesystems/speckle-server#1312]
## What package are you referring to?

viewer

## Describe the bug

When using the viewer with BOTH filters and layers, it does not behave as expected. When applying a filter - all elements are shown as "ghosted" regardless of whether they are hidden or not.

## To Reproduce

1. In the viewer, expand "data view" and hide some elements using the "eye" icon
2. These elements will be hidden in the viewer.
3. Add a filter (e.g. "Volume") and use the slider to filter the elements.

## Expected behavior

Filter should be applied and show only visible elements as ghosted if they fall outside of the filter criteria.

## Actual behavior

Hidden elements show up when "ghosted" then hide again when they get included in the "non-ghosted" filter set.

## Screenshots

Currently visible objects (without filters)
![image](https://user-images.githubusercontent.com/760010/212156211-0efce15f-8d43-4291-ad6f-6a76ec695066.png)

Ghosted objects included invisible ones. Only the visible objects should show as ghosted.
![image](https://user-images.githubusercontent.com/760010/212156574-39105e57-e811-458e-b3c7-f7dc3332fc39.png)

## Proposed Solution (if any)

Support both filtering and "ghosting" (aka isolation) correctly within the viewer so that they may be used simultaneously.

Having looked at the viewer code (specifically the FilteringManager) there appears to be a fairly convoluted logic to how visual state gets applied to each object. It might be preferable to more explicitly define the visual state for all elements and handle the logic for how those states get applied within the application state.

My hunch is that "command-based logic" is at the root of this and a stateful approach would solve it:
![image](https://user-images.githubusercontent.com/760010/212157057-a4505aa6-0212-4538-9f9b-e203ca83841e.png)

**Comment by AlexandruPopovici** [comment]
This issue is fixed in the latest iteration of FE2 and viewer API 2.0
