### ISSUE TITLE
Enhancement: Viewer -> support setting object opacity in setUserObjectColors

### ISSUE THREAD

**Issue by gouldingken** [specklesystems/speckle-server#1313]
## What package are you referring to?
viewer

## Is your feature request related to a problem? Please describe.
Unable to specify opacity for objects shown in Viewer

## Describe the solution you'd like
Support an opacity value in addition to the string value (or support an ARGB string as the "color" param). This would be applied to all objects in the given group using a transparent material.

**Comment by AlexandruPopovici** [comment]
No longer relevant. API 2.0 allows this out of the box via `setMaterial`
