### ISSUE TITLE
Speckle Server 1-Click image (DigitalOcean) - 502 Bad Gateway

### ISSUE THREAD

**Issue by Struct4** [specklesystems/speckle-server#1354]
Just now I got this error message when installing the 1-Click Speckle Server on DigitalOcean 502 Bad Gateway (nginx/1.18.0 (Ubuntu)). Am I the only one with this problem? And how can this be fixed? ~Struct4U

**Comment by benjaminvo** [comment]
Closing because stale. Reopen if still a problem
