### ISSUE TITLE
Section Box From Comment Jitters

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#1359]
Setting a comment should set the OG section box. Right now, we might be setting it twice (?) when a comment is opened. 

To reproduce, check this comment out: https://latest.speckle.dev/streams/85e05b8c72/commits/9875d5d3bf?cId=36354a7623

It will originally set the original section box, then a few frames later (possibly on thread load end), we're setting an expanded section box again.

**Comment by AlexandruPopovici** [comment]
Looks like it's caused by the existing issue here: https://github.com/specklesystems/speckle-server/issues/1231

**Comment by AlexandruPopovici** [comment]
Migrated to Jira
