### ISSUE TITLE
FreeCAD Connector

### ISSUE THREAD

**Issue by michacassola** [specklesystems/speckle-server#1368]
I would like to suggest a FreeCAD connector.
This way one could stay FOSS with FreeCAD <-speckle-> Blender.

**Comment by gjedlicska** [comment]
Hey @michacassola ,

Thanks for the suggestion, we're tracking new features and ideas on our forum: https://speckle.community/c/features/7

Please add your plus one there 🙂

**Comment by michacassola** [comment]
Thanks! Plus one as heart and comment were added: https://speckle.community/t/new-connector-request-freecad/2613
