### ISSUE TITLE
OIDC Error on trying to authenticate

### ISSUE THREAD

**Issue by Coolicky** [specklesystems/speckle-server#1374]
## Prerequisites

I've set up docker deployment with Speckle. 

I've managed to make the local strategy work fine.
I've managed to get Github strategy working. 

I'm using an Authentik self-hosted provider. Setup for OIDC, implicit flow.

the .env strategy as below.

STRATEGY_OIDC=true
OIDC_NAME="NAME"
OIDC_DISCOVERY_URL="https://DOMAIN/application/o/APP/.well-known/openid-configuration"
OIDC_CLIENT_ID="SOME_ID"
OIDC_CLIENT_SECRET="SUPER_SECRET"

The Authentik works fine with multiple apps already.

## Describe the bug
When going through auth flow i'm getting the following response.

`[{"err":"insert into \"authorization_codes\" (\"appId\", \"challenge\", \"id\", \"userId\") values ($1, DEFAULT, $2, $3) - null value in column \"challenge\" of relation \"authorization_codes\" violates not-null constraint"}](url)`

On server logs i can see:

{
  "level": "error",
  "time": "2023-02-15T16:41:41.984Z",
  "component": "modules",
  "err": {
    "type": "DatabaseError",
    "message": "insert into \"authorization_codes\" (\"appId\", \"challenge\", \"id\", \"userId\") values ($1, DEFAULT, $2, $3) - null value in column \"challenge\" of relation \"authorization_codes\" violates not-null constraint",
    "stack": "error: insert into \"authorization_codes\" (\"appId\", \"challenge\", \"id\", \"userId\") values ($1, DEFAULT, $2, $3) - null value in column \"challenge\" of relation \"authorization_codes\" violates not-null constraint\n    at Parser.parseErrorMessage (/speckle-server/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/speckle-server/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/speckle-server/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/speckle-server/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
    "length": 335,
    "name": "error",
    "severity": "ERROR",
    "code": "23502",
    "detail": "Failing row contains (339f2de06267921bccd047e8cbd3a8ee4d974fccf5, spklwebapp, 09782ac043, null, 2023-02-15 16:41:41.981864+00, 600000).",
    "schema": "public",
    "table": "authorization_codes",
    "column": "challenge",
    "file": "execMain.c",
    "line": "1959",
    "routine": "ExecConstraints"
  },
  "msg": "insertinto \"authorization_codes\" (\"appId\", \"challenge\", \"id\", \"userId\") values ($1, DEFAULT, $2, $3) - null value in column \"challenge\" of relation \"authorization_codes\" violates not-null constraint"
}

for the postgres logs:

`2023-02-15 16:41:41.982 UTC [30] ERROR:  null value in column "challenge" of relation "authorization_codes" violates not-null constraint
2023-02-15 16:41:41.982 UTC [30] DETAIL:  Failing row contains (339f2de06267921bccd047e8cbd3a8ee4d974fccf5, spklwebapp, 09782ac043, null, 2023-02-15 16:41:41.981864+00, 600000).`

I can confirm that the postgres table authorization_codes has a column challenge with "Not NULL?" enabled.

In my Authentik provider the action shows as authorized:

{
    "geo": {
//some location
    },
    "flow": "ID",
    "scopes": "openid profile email",
    "http_request": {
        "args": {
            "query": "client_id=CLIENTID&scope=openid+profile+email&response_type=code&redirect_uri=https://DOMAIN/auth/oidc/callback&state=UNIQUE_STRING&code_challenge=UNIQUE_STRING&code_challenge_method=S256"
        },
        "path": "/api/v3/flows/executor/default-provider-authorization-implicit-consent/",
        "method": "GET"
    },
    "authorized_application": {
        "pk": "ID",
        "app": "authentik_core",
        "name": "NAME",
        "model_name": "application"
    }
}

The user gets created inside the postgres db. 

Just to mess with it even more i removed the Postgress Null constraint which just leads to redirect to login screen after going through the following url

![image](https://user-images.githubusercontent.com/45921848/219114558-51ab69fa-0102-4c47-8836-c750e6d6b563.png)

Not sure if this is a problem with Authentik, or i might have misconfigured something. 

## System Info

Tried Speckle  speckle/speckle-server:2 &  speckle/speckle-server:latest
Tried "postgres:13.1-alpine" & "postgres:13.10-alpine"
to no avail.

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

**Comment by Coolicky** [comment]
Some additional info..

I've setup a dev instance of another OIDC provider,  [keycloak ](https://github.com/keycloak/keycloak)
Tested if the auth worked. There were no problems. 

When trying to use it for speckle got the identical error as in with authentik.

**Comment by didimitrie** [comment]
Thanks for reporting this @Coolicky! We're planning to look at it next week 🤞 - will keep you posted. It's weird that it cannot be reproduced with keycloak. 

Our (@gjedlicska & me) current thinking goes like this: the missing challenge is (theoretically) sent out by the frontend to the server when initiating the oauth flow, whether it's a local auth strategy (email + pwd), or third party (e.g., google).

Local: 
![local](https://user-images.githubusercontent.com/7696515/219450648-c3a5b855-8d96-4880-b93e-6bac3adf7142.png)

Google: 
![google](https://user-images.githubusercontent.com/7696515/219450995-04cc96c6-5787-4b38-8ce6-95ab9f77ce06.png)

Could you inspect on your end the network requests and see if the challenge is actually being sent when using the OIDC strategy? It will help us with our investigations. 

Specifically, if no challenge is being sent - it's a frontend issue (though this is unlikely, as it worked with the keycloak OIDC provider, but not your production one - unless - and this is important - the **deployment setup changed**). 

If the challenge is being sent, it might be a deployment issue or something related with how we persist session information on the server side across multiple server instances.

**Comment by Coolicky** [comment]
> Some additional info..
> 
> I've setup a dev instance of another OIDC provider, [keycloak ](https://github.com/keycloak/keycloak) Tested if the auth worked. There were no problems.
> 
> When trying to use it for speckle got the identical error as in with authentik.

Sorry i didn't realize i was confusing. What i meant is that the keycloak was working fine by itself. But trying to use it with speckle ended with the same error. I'll have a look to provide more detail on the weekend.

**Comment by Coolicky** [comment]
![image](https://user-images.githubusercontent.com/45921848/219463062-fb70f046-ff47-45b0-8844-fc66cfc14dcc.png)

The challenge gets sent

Goes through the authentik and authorizes.

![image](https://user-images.githubusercontent.com/45921848/219464150-19550826-a086-4ede-8604-4ab716f1057f.png)

Redirects to speckle

![image](https://user-images.githubusercontent.com/45921848/219464455-80da5d37-9cda-4e32-b4f9-7d039edf40cb.png)

Where speckle throws 401

![image](https://user-images.githubusercontent.com/45921848/219464844-2eb82890-05f5-46a8-b0de-3944ac2d8c91.png)

With an error as mentioned above.

![image](https://user-images.githubusercontent.com/45921848/219464951-2c41363b-11c9-4b5a-92f3-2918096f66cb.png)

Since the authentik and speckle were on the same server (same VM) i've check with another one on different domain just in case. 
The same error occured. 
I tried Okta too, the same error. 

The server is behind a nginx proxy manager instance that terminates ssl. If that could be the source of trouble maybe. But i tried running it on http:// and still get the same result. Attached the docker-compose file. If it is of any use I'm running the docker on Ubuntu 22.04.1 on Azure VM.
[docker-compose.txt](https://github.com/specklesystems/speckle-server/files/10760125/docker-compose.txt)

**Comment by gjedlicska** [comment]
Hey @Coolicky 
thanks for the detailed report on this issue. It helped me a lot in getting the issue fixed.

The linked PR #1394 is addressing the issue that you ran into.
We're planning on releasing this to our stable channel later this week after a bit of testing.

**Comment by Coolicky** [comment]
Thank You. I'll wait for release and update when ready.
