### ISSUE TITLE
Editing profile picture

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#139]
Something weird happens when uploading a new pic (it's a small square), and it can't be repositioned to be in the center:

![image](https://user-images.githubusercontent.com/2679513/110940112-4b4cf100-832e-11eb-8688-5d97c11dfcf4.png)

**Comment by simon-gd** [comment]
You can try getting rid of text-center style from line 24.
https://github.com/specklesystems/speckle-server/blob/8b69262e517af274b1c357b9170c1892e689fe46/packages/frontend/src/components/UserInfoCard.vue#L24

**Comment by teocomi** [comment]
🤦‍♂️ thanks @simon-gd !
