### ISSUE TITLE
Proposal: allow users to combine multiple streams, branches, and commits in the web viewer

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-server#146]
Users may want to combine multiple streams, branches, and/or commits (eg "latest") in the web viewer to visualize entire projects or subdomains of projects.

Bonus maybe feature: allow users to save these "view" settings and share them via url link

**Comment by AlanRynne** [comment]
After a quick chat with @didimitrie we've decided to park this until the Viewer package gets some well deserved love and attention, mainly #326.

Main blocker here is not having the ability to `unload` specific stream/branch/commit data, forcing us to reload the entire viewer every time the user changes one of the streams (adding is not a problem, but replacing cannot be done). It's not as straight forward as it would initially look, so for now we're closing this.

It will be done, just not now 😄

**Comment by teocomi** [comment]
@didimitrie can we close this after your latest updates?

**Comment by didimitrie** [comment]
Yes, we finally can :) 🎊
