### ISSUE TITLE
OIDC: name and organisation metadata is not being populated

### ISSUE THREAD

**Issue by iainsproat** [specklesystems/speckle-server#1468]
Users who register with Speckle Server via OIDC authentication, can register but their name and organisation is set to 'undefined'.

The `name` and `organisation` should be set to something appropriate.

Potential solutions which may be considered:
- these can be edited by the user after registering
- these can be set to a default by the server admin
- this could be populated from OIDC metadata.

**Comment by Chris-Welch-Aurecon** [comment]
Help!

![image](https://github.com/specklesystems/speckle-server/assets/131934793/4d022863-9025-4c29-8183-1685f0379310)

**Comment by alemagio** [comment]
I'll look into it.
