### ISSUE TITLE
Nested Instances and Materials

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-server#1481]
## Description

Tested this with some models. Worked fine in almost all cases. But i got a weird viewer result for one specific door.

Door handle has two materials that are overlapping. It has both door panels material and its own material. Ends up looking like a glitch in the viewer. Take a look at the screenshots below👇.

I am not sure if this this issue is related to viewer or Revit connector. I feel like it’s a viewer issue since when I examine the problematic model in an object level, it looks fine in the viewer.

## Screenshot

![image](https://user-images.githubusercontent.com/51519350/226893965-e4a9733f-2920-41d7-83fc-41fd50c7ad9a.png)

Door in Revit

![opera_gf4w9l3DmK](https://user-images.githubusercontent.com/51519350/226894091-93f07f51-edb0-4a21-a84d-6b74e98d7d07.gif)

Same door in the commit

![opera_DAZVkZilK9](https://user-images.githubusercontent.com/51519350/226894163-5f91ac43-5d7e-4f81-92f7-e2d618612995.gif)

Same door in the object viewer

### Related Commit

https://latest.speckle.dev/streams/e258b0e8db/commits/c0890dbc5e

### Door Object

https://latest.speckle.dev/streams/e258b0e8db/objects/667b84f618118868d5f5c23ee5eb785d

## Files Used

G:\Shared drives\All Company\07 Sample Models\Revit\Bilal's Models\IUHY Istanbul Hospital Project\01-Architecture\C Blok\IUHY-C-ZZ-M3-XX-AR.rvt

**Comment by AlexandruPopovici** [comment]
There is an issue with the data. The door knob is duplicated. 
Once in this instance: https://latest.speckle.dev/streams/e258b0e8db/objects/4ef4447a8b1c9fb880c76c42f1961fa5
And again in this instance: https://latest.speckle.dev/streams/e258b0e8db/objects/0030f5a9c6771f415e2d46470c6565d5

This might be connected to the a more general issue where streams from Revit duplicate both instances and non instanced incorrectly
