### ISSUE TITLE
bug(viewer): Speckle.Box rendered incorrectly

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-server#1485]
Box primitive generated with Specklepy SDK directly represents only two edge faces.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/760691/227596902-7926b82d-6aaa-4651-bbaf-abc9bbe67c7b.png">

https://speckle.xyz/streams/87a2be92c7/commits/5f5769fa73

**Comment by AlexandruPopovici** [comment]
https://github.com/specklesystems/speckle-server/pull/1813
