### ISSUE TITLE
Dispose() method in Viewer.ts

### ISSUE THREAD

**Issue by saschabul** [specklesystems/speckle-server#1544]
Would be great to have Dispose() method in Viewer.ts implemented :)

**Comment by Sticcia** [comment]
Any news about this?

We have a Vue3 web app with multiple routes.

When the viewer is loaded the first time it works fine:
<img width="500" alt="Screenshot_3" src="https://github.com/specklesystems/speckle-server/assets/5552940/973d086a-0651-457b-b5cb-0acd7c0354b9">

But after routing back to the same viewer component the shading breaks:
<img width="500" alt="Screenshot_4" src="https://github.com/specklesystems/speckle-server/assets/5552940/dbeab458-038c-4fab-9501-b5b62979abf3">
We do the following
```JS
onBeforeUnmount(async () => {
  if (viewer) {
    await viewer.unloadAll();
    viewer.dispose();
  }
});
```
The current implementation of `dispose()` says [`    // TODO: currently it's easier to simply refresh the page :)`](https://github.com/specklesystems/speckle-server/blob/3689e1cd58ec4f06abee836af34889d6ce474571/packages/viewer/src/modules/Viewer.ts#L664C26-L664C26)

Refreshing the page does solve the issue which can also be done with `location.reload()` but this causes a white page every time we change components.

Is there a better workaround?
I tried using `DebugViewer` and disposing of the WebGLRenderer but with no luck.

Thanks.

**Comment by Sticcia** [comment]
Hi again, do you have any information about a possible workaround for this issue? How can we properly dispose of the Renderer ourselves?

**Comment by AlexandruPopovici** [comment]
Hello @Sticcia 

Thank you for your patience! We we will be looking into this issue in the following days and will surely come back with a resolution

Cheers

**Comment by Sticcia** [comment]
Thank you so much for the great work!
