### ISSUE TITLE
IFC Serialization Issues

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#1625]
Report: https://speckle.community/t/unable-to-receive-ifc-deserialization-errors/5987/3

Maybe due to the RenderMaterial diffuse value being a float.

**Comment by jsdbroughton** [comment]
The community reported the same issue. https://speckle.community/t/unable-to-receive-ifc-deserialization-errors/5987/5?u=jonathon

Also failing on double for diffuse value. Ignoring the throw converts the whole commit.

Source: https://drive.google.com/file/d/19zRrDgB51AQkY0SYuH7XZ4WY9pbzwbsz/view?usp=drive_link

Commit:
https://speckle.xyz/streams/7208953f58/commits/39057f3690

Example object failing:
https://speckle.xyz/streams/7208953f58/objects/76ed39fb921f7c8a71c8eadcf3c04c59
