### ISSUE TITLE
Weird lines on my model elements in the Speckle model viewer

### ISSUE THREAD

**Issue by Gaschitz** [specklesystems/speckle-server#1659]
## What package are you referring to?

web viewer issue

## Describe the bug

all of my models look a bit weird because of some extra lines on their surfaces
![image](https://github.com/specklesystems/speckle-server/assets/57147683/fc04f2a6-c3f8-4665-97d1-54b767e1bf81)

## System Info

- OS: WIN11
- Browser: Chrome

All my drivers are updated
![image](https://github.com/specklesystems/speckle-server/assets/57147683/276af8b7-5c51-42ff-9a6a-83cb003a4c65)

**Comment by AlexandruPopovici** [comment]
Hi Agi,

Can you please give me the exact CPU model?

Thanks

**Comment by Gaschitz** [comment]
Sure, here it is: 

CPU

	11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz

	Base speed:	2.92 GHz
	Sockets:	1
	Cores:	4
	Logical processors:	8
	Virtualisation:	Enabled
	L1 cache:	320 KB
	L2 cache:	5.0 MB
	L3 cache:	12.0 MB

	Utilisation	20%
	Speed	2.68 GHz
	Up time	5:00:55:30
	Processes	353
	Threads	5165
	Handles	186760

**Comment by AlexandruPopovici** [comment]
Fixed by installing intel drivers https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

**Comment by Gaschitz** [comment]
Thank you!
