### ISSUE TITLE
Invite only setting is applied only after server restart

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#167]
To reproduce:

-> toggle invites only on
-> toggle invites only off
-> cannot register without an invite (need to restart the server)

**Comment by didimitrie** [comment]
fix: ensure `serverInfo` is always fresh and not retrieved once per session.

Where? In auth strategies: 
- https://github.com/specklesystems/speckle-server/blob/4d31d1bb78e6f55fb811fd9c51c98deab2dc2ea4/packages/server/modules/auth/strategies/local.js#L19
- https://github.com/specklesystems/speckle-server/blob/4d31d1bb78e6f55fb811fd9c51c98deab2dc2ea4/packages/server/modules/auth/strategies/github.js#L23
- https://github.com/specklesystems/speckle-server/blob/4d31d1bb78e6f55fb811fd9c51c98deab2dc2ea4/packages/server/modules/auth/strategies/google.js#L22

As well as in any of the functions in:
- https://github.com/specklesystems/speckle-server/blob/4d31d1bb78e6f55fb811fd9c51c98deab2dc2ea4/packages/server/modules/auth/strategies.js#L17
