### ISSUE TITLE
CONTRIBUTING.md deserves an update!

### ISSUE THREAD

**Issue by HimanshuMahto** [specklesystems/speckle-server#1835]
It's not a problem, but I think CONTRIBUTING.md would look amazing with an update!

Describe the solution you'd like
Maybe an update to CONTRIBUTING.md would be amazing.
Unlike other amazing repos, this repo's CONTRIBUTING.md looks plain and simple.

I think emojified, fun and precise version would be better!

Describe alternatives you've considered
An update would be amazing!

Additional context
If you are reading this, you are amazing! ⭐

Starred ⭐✔️
Thanks and regards
Himanshu

**Comment by HimanshuMahto** [comment]
@iainsproat made the PR please do review it.

**Comment by HimanshuMahto** [comment]
@iainsproat, hey please do review the PR.

**Comment by benjaminvo** [comment]
Hey, sorry we didn't act on your PR when you submitted it last year. I see the PR has since been closed so I'll also close this issue. Please reopen if you find the motivation!
