### ISSUE TITLE
Frontend: Profile page/Stream page doesn't load after login

### ISSUE THREAD

**Issue by cristi8** [specklesystems/speckle-server#190]
Right after login, clicking user profile picture in the top right corner and selecting `Profile` does not open the Profile page (only changes url path to `/profile`, but page doesn't change )

**Comment by didimitrie** [comment]
Okay, this is nastier. It appears it's because the newly added snackbars for notifications are not checking for null data (you get an empty subscription event always when the initial subscription is successful). 

Basically you can't access any page 🥳
