### ISSUE TITLE
Nginx client_max_body_size prevents sending the stream from Revit connector

### ISSUE THREAD

**Issue by zhukoven** [specklesystems/speckle-server#198]
### Expected vs. Actual Behavior

Default nginx config limits the request size to 1Mb, which prevents from sending a fairly small Revit view with total children count = 686 elements: 
`Remote error: https://SERVERADDRESS is not reachable.  Response status code does not indicate success: 413 (Request Entity Too Large).`

### Reproduction Steps & System Config (win, osx, web, etc.)

Send a full 3D Revit view with multiple Generic Models (194), Model lines (39).

Tested in the following environment:
- Revit 2020.2.3
- Latest Speckle Server docker deployment (updated 4/29/2021)
- SpeckleConnectorRevit v.2.0.0.0

### Proposed Solution (if any)

Increase the `client_max_body_size` value or introduce a warning/disclaimer to the end-user.
I've set the limit to `100m`, not sure about the perfect value though: this may be too much for the average user.
![client_max_body_size](https://user-images.githubusercontent.com/27201628/116529383-92467400-a8e5-11eb-8700-3358891b4a78.jpeg)

#### Optional: Affected Projects

This relates to Speckle Revit connector - https://github.com/specklesystems/speckle-sharp/tree/master/ConnectorRevit

**Comment by cristi8** [comment]
Hi @zhukoven ,

Thanks for spotting this.

I just included the fix in the latest release v2.2.9.

**Comment by zhukoven** [comment]
Hi @cristi8, thanks for the quick fix!
