### ISSUE TITLE
Stream created notification triggered when user him/herself creates a stream

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#201]
The user creating a stream should not get a "stream created notification".
To implement this properly, we need to add the concept of stream creator see #120 Otherwise, if a stream is created and shared at the same time there, is no way of knowing who created it and therefore prevent the notification.

**Comment by didimitrie** [comment]
Closing as stale. I'm pretending to be a bot; will reopen when we have the bandwidth.
