### ISSUE TITLE
Bug: Color Filtering is not coloring objects according to parameter values

### ISSUE THREAD

**Issue by ahofbeck** [specklesystems/speckle-server#2061]
The model was uploaded with the Revit Connector version 2.18.0 wip7. The Speckle server is version 2.18.4

The front end is not coloring the objects according to parameter value. In the image below the elements with "TWP" should have been green instead of brown. 

The page was refreshed and the filtering was repeated with the same result.

![image](https://github.com/specklesystems/speckle-server/assets/32340026/41ce36dd-7ffb-4a62-b72b-f8827fd8b800)

**Comment by AlexandruPopovici** [comment]
Hi @ahofbeck 

This issue should be already fixed on latest.speckle.systems and should be available soon in production. If you're experiencing it in latest.speckle.systems right now, could you please share the stream so we can look into it?

Cheers

**Comment by benjaminvo** [comment]
Closing. Fixed according to @AlexandruPopovici above. @ahofbeck let us know if it isn't the case.
