### ISSUE TITLE
unbale to login to speckle using keycloak

### ISSUE THREAD

**Issue by AlaEddineKhadraoui** [specklesystems/speckle-server#2063]
Dear speckle team,

i'm facing the below error when using keycloak to login to speckle server :

in keycloak side the redricte uri : https://my-domain/auth/oidc/callback

the configuration is correct in speckle side 

the error: 
![image](https://github.com/specklesystems/speckle-server/assets/68070233/136ae01c-25dc-409e-a143-fa0dca113061)

the logs from speckle server:

![image](https://github.com/specklesystems/speckle-server/assets/68070233/eb5f68d7-399d-46e3-8579-6a9468a4d464)

i made search about the error and found this:
https://stackoverflow.com/questions/63259184/node-with-express-session-issue

note that i'm running the speckle server 2.18.1

regards

**Comment by didimitrie** [comment]
Added context: https://speckle.community/t/error-implementing-keycloak-with-speckle-signon/9356/11
