### ISSUE TITLE
Secondary Matomo Tracker Value

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#220]
See this [thread in discourse](https://speckle.community/t/sentry-matomo-override-dsn/1334/5) for context. Ideally we'd be able to customise data to be sent to two places at the same time.

**Comment by peterjgrainger** [comment]
Maybe you could copy the pattern used by aws lambda with destinations https://aws.amazon.com/blogs/compute/introducing-aws-lambda-destinations/

**Comment by didimitrie** [comment]
Hi @daviddekoning! We're finally on this. 

**Server:** 

Some recent developments caused a flood of requests on `subscription streamUpdate` - a client accidentally doing requests from an infinite loop - that exploded our xyz logs. This left us inclined to remove all matomo logging from the gql routes whatsoever, as it made us realise it's not the best way to capture endpoint usage and health 😅 (implementing rate limiting would offer some protection, but only to a certain extent).

Within this context, I don't think that log level details make much sense. And since we're now thinking to remove matomo from the server, a secondary value seems a bit of a doomed effort. For server admins wanting more details from their servers:
- We're starting to scope the requirements around what an admin interface would look like. Likely it will include stats on streams - happy to hear more on this one. @AlanRynne will ping you when he gets on to it! 
- We'll be adding more prometheus output to capture gql endpoint data & other metrics, which you can use to display in your grafana dashboard. 

The whole part around event tracking and their destinations - we're starting this week to scope & implement the architecture behind a server bound activity log coupled with webhooks that will allow any other services to react to server bound changes. I'd keep the telemetry part separate! 

**Frontend:** 

We're happy to allow for a secondary tracker value in the frontend application, so we'll jump on that - if that's ok with you!

**Comment by teocomi** [comment]
Hey @daviddekoning checking in to see if the proposed solution of a secondary tracker value in the frontend application works for you?

**Comment by daviddekoning** [comment]
Hey @teocomi, my apologies for the delay. The server bound activity log sounds interesting as we have a couple of applications that want to react to changes in Speckle streams. Secondary trackers on the front end sounds great!

**Comment by didimitrie** [comment]
Hey peeps! We forgot to follow up on this one. We haven't actually implemented it, but what we've done is something better & definitively cooler that provides some key activity metrics per month from the server you're an admin at: 

![Screenshot 2021-06-24 at 21 50 09](https://user-images.githubusercontent.com/7696515/123330648-30496a00-d536-11eb-8d21-1315286fe70a.png)
_(from our internal testing server - don't ask me how a six people team has 70 accounts registered. I think I might've run the user tests against our server by accident once or twice 😬)_

What you see is some key stats - total number of users, streams, commits and objects. We've also included historical data on said metrics which can help you identify nicely how active your server is by actually seeing how many streams, commits and objects are created each month. 

There's an api endpoint for this, of course - so you can basically request the data behind @AlanRynne's  fancy graphs and plop it wherever you want to! 

For this, you will need a personal access token generated by an admin user that includes the `server:stats` scope:
![image](https://user-images.githubusercontent.com/7696515/123331420-2f650800-d537-11eb-93e0-ebfe7b62e848.png)

Alternatively, just have an admin log in to the `/explorer` and you're good to go for executing that query. 

I'm going to close this issue for now; the activity stream is almost backend ready, and @cristi8's wrapping up webhooks too, so all the rest will be unblocked in good time. I should probably cross-post this to the forum too :D
