### ISSUE TITLE
Enhancement: Version id (fka commit id) no longer accessible in viewer - Add "Copy Latest Version ID" to Model Card Actions

### ISSUE THREAD

**Issue by stephenburgess8** [specklesystems/speckle-server#2243]
## Prerequisites

- [X] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [X] I checked the [documentation](https://speckle.guide/) and found no answer.
- [X] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [X] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [X] I'm requesting the feature to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

## What package are you referring to?

frontend-2 only

## Is your feature request related to a problem? Please describe.

In the previous version of the speckle server, the commits page provided a view of the commit including, crucially, the commit id. Information about that can be seen on this documentation page: https://speckle.guide/user/web.html

![image](https://github.com/specklesystems/speckle-server/assets/6003351/b8a85fbf-9ac6-4a2f-a21a-7ebe2b39c2de)

In this image from that page, the "id" at the top refers to the id of the commit (now I believe this is called the version id). In the new version of the Speckle Server frontend, there is no equivalent view of the old "Expand Data View" of the commit object. (note: please let me know if it is available and is something that I've missed).

When using `specklepy`, it's necessary to know the "commit id" to get the latest model. Our team had developed a workflow where we grabbed the latest commit ID from the expanded data view of the commit object when getting a project from our server instance. It would be nice to be able to access the version id in a way similar to how we used to access the commit id when we developed that workflow.

## Describe the solution you'd like

It would be nice would be to add a command to "copy the latest version ID" to the actions on the model card on the project models page.

<img width="420" alt="Screenshot 2024-05-03 at 3 10 50 PM" src="https://github.com/specklesystems/speckle-server/assets/6003351/7daae10f-d5b6-46bd-8c1b-4c833d81460f">

On the Models page for the Project, each Model (fka branch) has a drop down with options to copy the model id and the link. Since this model (branch) currently has its HEAD at the latest commit/version, it would make sense in my mind to provide a way for the user to copy the commit id at HEAD.

https://github.com/specklesystems/speckle-server/blob/2ba6b240ef927500c9d779d0bc16f7de9ef387b1/packages/frontend-2/components/project/page/models/Actions.vue#L109 

## Describe alternatives you've considered

If it would be easier to make the version id copy accessible on the `ViewerResourcesViewerCard` that might work. That's the view showing the graphical list of versions for a model

The latest version id is used in the calculation of the props for each `ViewerResourcesViewerCard`. If it's accessible there I would assume it should be accessible elsewhere, hence my suggestion of adding it to the Model card dropdown.. https://github.com/specklesystems/speckle-server/blob/2ba6b240ef927500c9d779d0bc16f7de9ef387b1/packages/frontend-2/components/viewer/resources/ModelCard.vue#L86

I found out that the version id is used here because the latest version id is actually embedded in the url of the preview image.

<img width="399" alt="Screenshot 2024-05-03 at 3 37 17 PM" src="https://github.com/specklesystems/speckle-server/assets/6003351/0939539d-591d-49bb-9679-4b449613a220">

The other alternative I've considered is a purely programmatic one in python. However it's possible others may find utility from having the latest version ID easily accessible in the speckle server frontend, so I wanted to propose it. 

## Additional context

I have experience working with Vue so I'd be willing to give this solution a shot if that would help.

Thanks for your work on this project.

## Related issues or community discussions

I searched issues and community discussions but I couldn't find another reference to this.

**Comment by didimitrie** [comment]
Hi @stephenburgess8, we've recently introduced "dev mode" which brings back a similar view of your commit in FE2: https://github.com/specklesystems/speckle-server/pull/2296

Would this be enough? Do note, we're not against adding that option to the model card (cc @benjaminvo)

**Comment by benjaminvo** [comment]
Hi @stephenburgess8! Thanks for the thorough request.

On top of what Dim says, the latest version ID is also accessible from the versions page so I'm hesitant to add it to the model card (the versions page is not easy to find though but that's a separate issue). 

![CleanShot 2024-06-11 at 14 15 03@2x](https://github.com/specklesystems/speckle-server/assets/2694102/536ae924-e5ae-4768-b295-85872dc62330)
![CleanShot 2024-06-11 at 14 12 35@2x](https://github.com/specklesystems/speckle-server/assets/2694102/42ea57eb-f8ad-4235-a291-65df6e8e7015)

I'm hesitant to add it to the model card too
