### ISSUE TITLE
Viewer: usability enhancements laundry list

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-server#236]
To be discussed further:

- [ ] Single-click object labels: currently the user needs to click once to reveal a label in the object explorer, and then again to expand. Automatically generating the labels on load would be much more informative and improve quality of life for anyone using the object explorer (bonus this behavior could be propagated to the excel connector)

**Comment by didimitrie** [comment]
If this is regarding the selected object behaviour, totally!
