### ISSUE TITLE
Delete/Edit Branches Got Lost

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#239]
Editing of branches does not have an UI outlet anymore (including branch deletion).

**Comment by teocomi** [comment]
It's there but quite hidden given the latest reshuffling of the frontend: 

Select a stream > select the branch in the dropdown > click see all commits > you get to the "branch" page. From there you can edit/delete a branch.

Cc @clairekuang 

The easiest solution, for now, is probably to move the edit button to the page with the branches dropdown.

![image](https://user-images.githubusercontent.com/2679513/118157186-264e2a80-b412-11eb-811f-dd757ba119fe.png)

**Comment by didimitrie** [comment]
okay, fixed labels and priority on this one then!

**Comment by teocomi** [comment]
Added friendly new button 
![image](https://user-images.githubusercontent.com/2679513/121235452-d20d5d80-c88c-11eb-8b35-6651077f8549.png)
