### ISSUE TITLE
Dynamic client registration and connector authorisation flow

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#27]
This is a bigger issue, spanning across more than one repo ultimately. 

### Expected Behaviour Proposal

The goal is to make an end-user's account creation/login/registration flow as easily as possible. In 1.0, it's a bit of a mess as you can add accounts from all over the place, and it's rather confusing. 

In 2.0, we'd want to have the experience streamlined. Here's a preliminary proposal: 

1) User navigates to a server. He is then prompted to log in or register via the available strategies on that server. 
2) On successful authentication, the user is redirected to the main web application (the frontend). 

Upon reaching this stage we need to determine if it's the user's first session on that server. 

3) If it's the user's first session, display a nice _dismissible_ banner/ui element asking to 
  - (a) download and install the speckle manager
  - (b) or, if they have done that already, "click here" to register their desktop connectors. 

4) If it's not the first time, carry on as usual :) 

The (3.b) behaviour entails opening up a custom application scheme, the way slack and others do it (ie, `speckle://manager?args`, and launching into the oauth2 flow from the manager itself. 

### The Gist

- each individual server's frontend becomes the one stop place to add an account _to that server_. 
- you cannot add accounts from clients, etc.

This helps us keep a secure auth flow for clients (prevents impersonation by other apps), and hopefully simplifies confusion on the user's side, as much as we can in the distributed many speckle servers scenario. 

### TODOs

To make this work, several things need to happen: 
- update the manager to register a custom app scheme on windows, so it can be launched from the browser
- update the manager to be able to dance the oauth flow & store an account on the user's computer
- dynamic client registration for connectors on the server the first time a user authenticates
- frontend needs to check wether it's the user's first time here (server models need to be updated, or use a cookie?)

#### Optional: Affected Projects

Server, Frontend, Core and the Speckle Manager.

**Comment by daviddekoning** [comment]
You mention registering desktop clients, but would this also work for web clients (e.g. Arup Carbon, workflow orchestration tools, etc...)? We expect web clients to grow in importance in the near future. I am assuming it will, since lots of others (e.g. github) do allow this.

It is important for us to be able to set up cloud-based clients to connect to Speckle servers as specific users - either specific individuals, or service accounts.

**Comment by didimitrie** [comment]
> You mention registering desktop clients, but would this also work for web clients (e.g. Arup Carbon, workflow orchestration tools, etc...)?

Yes, totally. The server itself already kind-of demonstrates that; we have yet to document the behaviour, but try going over to localhost:3000/explorer on a test server (don't forget to run `npm run dev:frontend` too) - it's a mock frontend application. 

For other cloud based clients, ie automation scripts, we've embedded the capacity to generate "personal api tokens" with limited scopes, etc.
