### ISSUE TITLE
Frontend: Change font to Space Grotesk

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-server#277]
Headings only. Current problem: on windows the font does not load.

**Comment by teocomi** [comment]
Related to this, some fonts are missing on a brand new Win machine: 

![image](https://user-images.githubusercontent.com/2679513/124133576-de469e00-da79-11eb-9a4a-b0aa35dd8404.png)

**Comment by AlanRynne** [comment]
🤦🏼‍♂️ This has happened to me at random times, haven't figured out whats the problem. The font that appears is neither our `Space Grotesk` nor the fallback one provided by google fonts 🤷🏼‍♂️
