### ISSUE TITLE
Viewer: Confusing handling of root commit object property `data`

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-server#282]
### Expected vs. Actual Behavior

It seems that a property called `data` on the root commit object causes some unexpected behaviour for streams not coming from Grasshopper.

In @AlanRynne's ifc test stream, none of the objects within a single base under the `data` field on the root commit showed up. Making this a list of the one base rather than just the base itself caused the objects to show up (eg `data: [obj]` rather than `data: obj`).

In this blender stream, only the object within the root `data` field show up - other objects on the root are skipped.

- [here](https://latest.speckle.dev/streams/0c6ad366c4/commits/c52cfd5a54) is the borked commit
- [here](https://latest.speckle.dev/streams/0c6ad366c4/commits/8141f58152) is a fixed commit (changed `data` field to `objects`)

**Comment by didimitrie** [comment]
@izzylys, is this still happening? I haven't heard anything re it in a while, but this doesn't mean it's not active still 😬

**Comment by izzylys** [comment]
yep we never fixed this! as mentioned in the issue, i got around it in Blender by changing the `data` field to be called `objects` so it's not a problem for blender. but it is still a problem that there is some special handling of the `data` field on a root commit obj

**Comment by izzylys** [comment]
bumping this just bc i got stuck again debugging something only to realise it was this issue 🤡

so here's another one - geo ignored bc it is within a `data` prop

https://latest.speckle.dev/streams/73539e248d/objects/2e2ae95239035884b8d612030f598918
