### ISSUE TITLE
Iframe: Separate embed feature to it's own app

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#289]
![image](https://user-images.githubusercontent.com/2679513/121714762-12abe780-cad6-11eb-820a-e5d5666fa2ed.png)

**Comment by AlanRynne** [comment]
Proposed solution for this is to create 2 separate Vue apps, the frontend with all it's fancy features, and a dumb one with only the embed component. Initial boilerplate on how to build 2 apps at once is here:

https://github.com/specklesystems/speckle-server/tree/alan/frontend/embed-viewer-fix

We need a chat with @cristi8 to see what changes would be required server side / in deployment for this to work properly:

Ideally:

- Embed app would live in `/embed`
- Every other route would live in `/`, as it currently works.
