### ISSUE TITLE
Frontend: globals permissions

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#296]
Think this one escaped us: a user can try and create globals in any stream (without any effect, of course). Things to check/todo:
- [ ] hide globals button from sidebar if user is not in collabs list
- [ ] disable any edit/create functionality if user role is not contributor+

P2 as not life threatening, but should be checked/implemented pre-release.

**Comment by izzylys** [comment]
hmm so currently yes anyone can see the globals, *but* the save button is only visible if you are a collab. if you don't have write permission, the save button disappears and there is an extra para above the globals saying you are free to play around, but you don't have the required stream permissions to save any changes. I did it like this bc I thought anyone should be able to see the globals (and see the fun draggable ui 😜) even if you aren't allowed to edit them. however, if you disagree then yeah totes we can hide the globals button completely.

**Comment by didimitrie** [comment]
Good morning! Makes sense. The only thing I'd hide/disable/catch/explain in a nice way then is the case where 
- I'm in a public stream with no role
- no globals exist
- create globals button is nice friendly but can't do anything

Maybe just disabling it is enough, with a friendly tooltip...
