### ISSUE TITLE
Stream visibility not updating with StreamUpdate mutation 

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#30]
Streams visibility is not affected when setting the `isPublic` property on a `StreamUpdate` mutation.
This is because the mutation currently only works on name and description.
There is a `updateStreamPrivacy` service on the server but it's not exposed via the API.

The resolution is to either expose it and remove `isPublic` from `StreamUpdateInput` or have the `StreamUpdate` mutation also change visibility.

**Comment by didimitrie** [comment]
Sneakily closed in #63. Fix was easy, given that only stream owners can update a stream's description, name and visibility.
