### ISSUE TITLE
Embed: Viewer does not work on sandboxed iframe.

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-server#307]
As reported here -> https://speckle.community/t/3d-models-visuals-in-power-bi/1429/6

What I think is happening is that the `iframe` is being automatically loaded with the `sandbox` attribute, which means extra security rules apply.

Tried hacking it by adding the `allow-same-origin` attribute but same happens. We should look further into this, as I'm sure its not the only platform that will do this.

**Comment by teocomi** [comment]
Dupe of https://github.com/specklesystems/speckle-server/issues/289
