### ISSUE TITLE
Embed button doesn't copy data to clipboard

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-server#319]
### Expected vs. Actual Behavior

Clicking embed button should copy the embed link into the clipboard. It doesn't add it to the clipboard, so cannot paste the link anywhere.

### Reproduction Steps & System Config (win, osx, web, etc.)
Using the lastest speckle server 2.2.19, load a commit in the viewer, click on either embed url or embed iframe. The url should be copied into the system clipboard.

Tested platforms and browsers: chrome and firefox on linux and android.

Console output attached
![image](https://user-images.githubusercontent.com/57442769/123815552-e0342400-d8f6-11eb-92c6-38df45f12ba6.png)

**Comment by didimitrie** [comment]
Seems to have been fixed!
