### ISSUE TITLE
Add preview images to frontend meta tags

### ISSUE THREAD

**Issue by cristi8** [specklesystems/speckle-server#322]
When pasting a link on different social platforms, we can set an image for that link to be shown to the users

- [x] Server endpoints to return preview images
- [x] Frontend meta tags

**Comment by cristi8** [comment]
Added new endpoints that return images:
```
/preview/:streamId
/preview/:streamId/branches/:branchName
/preview/:streamId/commits/:commitId
/preview/:streamId/objects/:objectId
```

**Comment by didimitrie** [comment]
Frontend meta tags won't work - it's a SPA so if you want to set meta tags JS needs to run (it doesn't when fb/twitter/etc. create link previews by trawling through meta tags). 

Potential solution (A) would be to bypass based on user agent the frontend application on the server side into a special route that generates a stub html page with the required meta tags, inc. preview image. This might cause confusion with client code that most likely doesn't have a user agent set (?). 

Potential solution (B) would be to switch to SSR (via nuxt). I'm not keen to do this, as it's a massive change (complete re-write most likely) on the frontend.

**Comment by cristi8** [comment]
Hmm, I think the following might work:
- Have our SPA have generic link preview stuff "Speckle Web App" and the logo as image
- Have nginx substitute those social link preview values for requests on the paths that we are interested in (those requests go through the frontend's nginx, where we can easily make a lua script to replace the values)

What do you think about this? It would keep everything separated and efficient
