### ISSUE TITLE
Viewer: Misc Wishlist

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-server#326]
Several different things I wish the viewer had, or I did not know how to do. We should properly scope them, split them into separate issues and close this one 👍🏼

- [ ] **HIGH PRIORITY** (at least for me 😅 ): `d.ts` files for proper autocomplete when using `npm` package.
- [x] Being able to individually `unload` independent streams (techincally, commit objects....).
- [x] Being able to distinguish in the viewer what object comes from what stream (stream grouping?).
- [x] Being able to color entire streams (or parts of it) with a simple function.
- [x] Possible bug, unloading all geometries doesn't get rid of the `loaders`. Leaving to duplicated loaders in the array.
- [x] Support the diff endpoint natively
- [ ] Viewer currently only works by "fetching" commits from the server, but could also work by passing the `speckle objects` in directly (any refs should/would be fetched).
- [ ] Automate `npm` publish on our CI.
- [ ] Material problems from revit: https://speckle.community/t/revit-connector-colors-materials/1677

**Comment by clairekuang** [comment]
- [ ] custom views in embedded viewer has weird UI when the list is too long
![image](https://user-images.githubusercontent.com/16748799/124737535-f30ab200-df0f-11eb-9de5-91313291a35a.png)

**Comment by teocomi** [comment]
Agree @clairekuang maybe custom views could be sub-menus

**Comment by AlanRynne** [comment]
Closed #146 due to huge blocker on this side of things. Once we get to loading/unloading different models properly we should re-open it and scope it accordingly.

**Comment by teocomi** [comment]
Adding some feature requests from the community (Rasmus):

- P1 have multiple design in 1 stream, and use attributes to change their visibility
    - specify visibility setting via URL embed
    - like the layer book in rhino 7
    - to share with clients & stuff
- P2 since all rebars have attributes
    - have a tabular interface specific for rebar elements
    - interface to define joints from speckle viewer (basically setting a prop on them)
- P3 construction phases & stages
    - display sequencing in viewer like other 3d viewers

**Comment by AlanRynne** [comment]
One more! 🙌🏼  Handle massive amounts of data in the viewer:

Huge point cloud does not get displayed on the web viewer. When loading [this stream](https://speckle.xyz/streams/78f797f5b4), I get the following generic error:

<img width="547" alt="Screenshot 2021-09-01 at 22 55 23" src="https://user-images.githubusercontent.com/2316535/131959383-5384fcf2-f795-41d5-9932-9735d430be97.png">

I suspect the final array of values is just too big to handle?

**Comment by didimitrie** [comment]
Coming from the forum, adding a **convention proposal**: if an object has a metadata field, on selection just show that rather than the whole default view (possibly with some markdown parsing!). This is useful for being able to convey quick information in digestible form.

**Comment by teocomi** [comment]
This will be tackled right after https://github.com/specklesystems/speckle-server/issues/393 as there are various overlaps.

**Comment by izzylys** [comment]
poss bug: nested block definitions ending up with wrong translation 

https://latest.speckle.dev/streams/481735d5b9/commits/c60c688be7

**Comment by didimitrie** [comment]
> poss bug: nested block definitions ending up with wrong translation
> 
> https://latest.speckle.dev/streams/481735d5b9/commits/c60c688be7

can we have an isolated element to test with? iirc nested block transforms were implemented using the rhino as samples, and IIRC standup time today, there were issues sketchup < > rhino too, so there might be an underlying issue somewhere...

**Comment by clairekuang** [comment]
The underlying issue with Rhino is that Rhino doesn't like empty block definitions (defs that only contain instances that contain defs with only instances) - so sending from blender seems to be correct, and the viewer may have a similar issue as rhino re: nesting

**Comment by izzylys** [comment]
https://latest.speckle.dev/streams/f54cd597bd/commits/7754023b7c

i think it's a viewer and rhino issue as there aren't any problems in autocad and unreal (which both fully support mega nested blocks

**Comment by didimitrie** [comment]
closing this as most of the stuff is done!
