### ISSUE TITLE
Viewer: Embedded viewer doesn't show referenced object when exploring selection

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-server#327]
### Expected vs. Actual Behavior

When expanding the referenced object, nothing shows up below the header
![no expanded ref obj](https://user-images.githubusercontent.com/7717434/124721396-fe0a1600-df00-11eb-8600-976b1574a40b.png)

When clicking through to open the object in the web, the URL is incorrect as the stream id is null
![invalid object url](https://user-images.githubusercontent.com/7717434/124721648-33aeff00-df01-11eb-8246-b47debb23eb8.png)

### Reproduction Steps & System Config (win, osx, web, etc.)

You can try it yourself with the second embed on this post:
https://speckle.community/t/pyspeckle-2-0-is-starting-to-take-shape-be-an-early-tester/1084/22?u=izzylys

This is the commit:
https://speckle.xyz/streams/a2160817ac/commits/f32fb4cd07

**Comment by didimitrie** [comment]
closing as we stopped displaying selection info. too much of a hassle in incognito windows and such.
