### ISSUE TITLE
Viewer: views sent from Revit do not show up in Select View, and have weird boxes

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-server#328]
### Expected vs. Actual Behavior

When sending 3D views from the sample architecture file in Revit, the views do not show up as options in the viewer's "select view" list. Also, they come with weird boxes.

### Reproduction Steps & System Config (win, osx, web, etc.)

Stream with everything sent from the sample arch model in revit: [https://speckle.xyz/streams/043f36511f/commits/ad21eabbab](https://speckle.xyz/streams/043f36511f/commits/ad21eabbab)
Stream with just 3D views sent: [https://speckle.xyz/streams/043f36511f/commits/dea4c2885f](https://speckle.xyz/streams/043f36511f/commits/dea4c2885f)

**Comment by didimitrie** [comment]
Hi @clairekuang - it seems it's because I've assumed the `target` prop will always be there, and these views don't have it. This causes the conversion to throw, and then we iterate through any props and... find the displayable bbox. 

Is the target property guaranteed to exist or not? If not, I guess I could calculate a target based on the "forward" vector and scene bounding box or something (it would be easier though if views had a target!).

**Comment by clairekuang** [comment]
I removed the target prop from the revit converter in the last round of debugging - it was previously being manually calculated which I suspected may have messed up a few revit to rhino conversions. Rhino was doing a decent job automatically adjusting the target when the view doesn't contain one. I can try adding the calculated targets in revit back in and running a few tests before you try it in viewer!

**Comment by didimitrie** [comment]
Roger! And maybe in the Rhino conversion, we can ignore the target if it's doing a better job by itself? My 0.02£, coming from someone who didn't work on those conversions at all...

**Comment by clairekuang** [comment]
Added the target prop back in so the views from Revit are populating now, but unforch the objectid is being used instead of their name prop. Sample stream: [https://speckle.xyz/streams/5dfbeb49c9/commits/dc5c07302f](https://speckle.xyz/streams/5dfbeb49c9/commits/dc5c07302f)

**Comment by didimitrie** [comment]
Yay, closing!
