### ISSUE TITLE
Speckle API docs are ridiculously hard to find. 

### ISSUE THREAD

**Issue by tluth** [specklesystems/speckle-server#330]
### Expected Behavior

I'd expect there to be a link to the api docs somewhere under dev docs on the documentation website

### Actual Behavior

When on the speckle webiste I click on "friendly API" under the Developers tab. It takes me to https://speckle.guide/. I click on "developer docs". There's still no link to the api docs. I click "user guide" and end up back at //speckle.guide. After 5 minutes of clicking around I realise that all the links on all the pages just seem to lead you in loops and there's no apparent structure to it. I can't find the page I'm looking for so I have to search through my history for all mentions of speckle. Eventually after some digging I find it at https://speckleworks.github.io/SpeckleSpecs/#speckle

### Reproduction Steps & System Config (win, osx, web, etc.)

Try find the openapi docs for speckle. Inevitably fail. 

### Proposed Solution (if any)

Maybe I'm just missing something really obvious, but it seems like there should be a link to this page under developer docs. It'd also be nice if there was a clearer structure to the website with some hierarchy rather than these ambiguous pages that are filled with links back to previous pages that you've inevitably already visited.

**Comment by teocomi** [comment]
Hi @tluth !

Thanks for the feedback, we do have API docs quite visible on our [dev docs page](https://speckle.guide/dev/), both for our GraphQL and REST APIs:

![image](https://user-images.githubusercontent.com/2679513/124927308-65ee5880-dff6-11eb-986d-0e84ce3912fb.png)

The SpeckleSpecs page you found is for the old Speckle v1 API.

**Comment by tluth** [comment]
Ahh right, thanks @teocomi 

I guess I just didn't look hard enough. I figured those other docs were outdated, but it'd be nice to get something similar for v2

**Comment by teocomi** [comment]
True, the GQL playground is not as nice as those old docs, but it provides all you need, plus it's self-documenting and always up to date :D

https://speckle.xyz/graphql

You can also use our flavoured explorer that lets you run queries as the logged user:

https://speckle.xyz/explorer

![image](https://user-images.githubusercontent.com/2679513/124930929-a3081a00-dff9-11eb-8933-8a5c85f32e96.png)
