### ISSUE TITLE
Some endpoints of the REST API doesn't require any authentication

### ISSUE THREAD

**Issue by trygveaa** [specklesystems/speckle-server#336]
### Expected vs. Actual Behavior

I registered an account at speckle.xyz and created a stream. When I try to use the REST API, I see that the endpoints that should require read permissions on the stream doesn't actually require any authentication at all.

E.g. https://speckle.xyz/objects/7bf1ae95d2/492441809cb55cb967586d25130c3106

I can just GET this directly, without any authorization header. The same goes for `/objects/:streamId/:objectId/single`. It seems like `/api/getobjects/:streamId` doesn't require any authorization either, but it just hangs for me, so not sure.

The endpoints that require write permissions (`/api/diff/:streamId` and `/objects/:streamId`) does return 401 if I don't provide an authorization header.

### Reproduction Steps & System Config (win, osx, web, etc.)

Just open the above url without setting any authorization header, e.g. `curl https://speckle.xyz/objects/7bf1ae95d2/492441809cb55cb967586d25130c3106`.

**Comment by didimitrie** [comment]
Hi @trygveaa! That's because the stream's visibility is set to public (ie, opening https://speckle.xyz/streams/7bf1ae95d2 in an incognito window will show it too) - so read operations are allowed. 

PS: in the future, please see [here](https://github.com/specklesystems/speckle-server#security) how to report potential security vulnerabilities :)

I'll close this issue for now, but feel free to keep the conversation up here if any other concerns!

**Comment by trygveaa** [comment]
> Hi @trygveaa! That's because the stream's visibility is set to public (ie, opening https://speckle.xyz/streams/7bf1ae95d2 in an incognito window will show it too) - so read operations are allowed.

Ah, sorry, I hadn't noticed that. Is it a good idea to have the visibility set to public by default though?

> PS: in the future, please see [here](https://github.com/specklesystems/speckle-server#security) how to report potential security vulnerabilities :)

Okay. This should be mentioned in https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md which is what is linked to when you try to create an issue.

**Comment by teocomi** [comment]
Contrib docs updated, thanks for the heads up!
