### ISSUE TITLE
Server: subscriptions for timeline & activity

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#361]
It would be good to refresh the timeline/activity when new events are created, prolly just one subscription like `activityCreated` is enough?

**Comment by didimitrie** [comment]
The timeline & activity is fed mostly in a similar fashion as the subscription events, which we should prolly use for this purpose. Wouldn't the subscription events serve? (pending refactoring their payloads to match activity timeline payloads).

**Comment by teocomi** [comment]
Not really, because in order to use branch, and commit subscriptions you need to specify a stream id, same goes for stream updated...

**Comment by didimitrie** [comment]
One solution that would require much less effort is to use polling. We're closing for now, as we also want to rethink the whole activity stream sooner or later. See [last planning session](https://www.notion.so/speckle/Web-Team-Flip-Planning-0b6890eaf51146e89f9cee1056f76637).
