### ISSUE TITLE
Frontend Laundry List

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#366]
1) Differentiate activity cards better. 
- [x] add main action buttons where applicable (e.g., stream created -> "View Stream"; contributor added -> "View Contributors", etc. )
- [x] add commit preview image in commit activity card (small, on the right, can be main action button replacement)

2) Various: 
- [x] Unify timeline layout (home page: right only; stream centered; go for right side in both views?)
- [ ] Do not display empty events (where nothing changed)
- [x] Breakpoint issues (see screenshot below)

3) Overall layout clarification and improvements
- [x] conflicting sidebars, top menus, profile picture menu, etc. especially critical when viewing a stream in small form factor devices. 
- [ ] we feel we can make the home view of a stream better :D 

Let's hope this list will grow with actual user feedback 🤞

**Comment by izzylys** [comment]
- [ ] maybe make urls in stream descriptions clickable links?
- [ ] smol thing, but i think these pills should either be clickable or not have the change on hover (also the tooltip for date is a bit wonky)
![image](https://user-images.githubusercontent.com/7717434/128034142-9d4314ee-9b6a-47cc-b426-e96f80d8b046.png)

**Comment by AlanRynne** [comment]
- [ ] Expand invite button so that it fills the entire max-width
![image](https://user-images.githubusercontent.com/2316535/128036520-937f387b-11c4-4f2a-b01d-b32640723d59.png)

**Comment by teocomi** [comment]
Implemented most of these in #368 , what's outstanding:
- [ ] do not display empty events. Not simple to do right not, better tackled when (if ever) we'll be grouping similar activity items
- [ ] breakpoint issues. Cuz I hate breakpoints
- [ ] overall layout clarification and improvements

**Comment by teocomi** [comment]
Ah! that probably was lost when I removed the edit dialog 😅

**Comment by cristi8** [comment]
![Untitled](https://user-images.githubusercontent.com/2551138/128940461-e4423209-51c3-4cfb-b815-1dc18cd57645.png)
Is this a known issue? I don't see any previews because all requests are for `https://latest.speckle.dev/preview/undefined`
