### ISSUE TITLE
Uniquely name new random streams

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#373]
New streams are all named "Random Stream", if you create multiple it gets hard to identify what is what, without looking at their id.
I'd like to randomly assign them unique names with some sort of library a bit as google does to anonymous docs viewers.

Eg: https://www.npmjs.com/package/unique-names-generator

**Comment by gjedlicska** [comment]
Hey @teocomi, what is the usecase, where we are creating streams without name? The frontend form field is required ATM.

**Comment by izzylys** [comment]
@gjedlicska all streams have a name, but as the issue says they are always called "Random Stream" if you don't provide one. this happens in the server in the stream create resolver if no name is provided (so all connectors are able to do this)

**Comment by izzylys** [comment]
note `name: name || 'Random Stream'`
https://github.com/specklesystems/speckle-server/blob/aa38cf9208747ce4c2dc98a5479cabaee23ffc3a/packages/server/modules/core/services/streams.js#L14-L30

**Comment by gjedlicska** [comment]
Thanks for the reply @izzylys the missing piece was, that all api components are allowed to create a stream object without name / name set to `null`.

**Comment by didimitrie** [comment]
And to specify a bit more, let's have thematic aec bound stuff. Format like `${RandomAdjective} ${RandomNoun}`. 

Adjective pool: Pink, Tall, Warm, Glowing, Shiny, Speckled, Blue, Stretched, Round, Plunky, etc.

Noun pool: Building, House, Treehouse, Plank, Nest, Tower, Tunnel, Mine, Brick, Wall, Fence, Structure, Edifice, Palace, Castle, ... ok out of inspiration now. 

Let's also get the community to source these!

**Comment by teocomi** [comment]
> Let's also get the community to source these!

How about we make a public google sheet to crowdsource these?
