### ISSUE TITLE
Server registration form not playing nicely with password managers

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-server#383]
### Expected vs. Actual Behavior

I tried to register a new user on speckle.xzy, and my password manager (1password) was not able to pick up the correct fields.
The username is switched with the organization name.

### Reproduction Steps & System Config (win, osx, web, etc.)

I'm using 1password for this, fill the forms, and this is what i get:
![image](https://user-images.githubusercontent.com/57442769/130323238-9f38df3d-8247-4086-8cee-d6b932ae347f.png)
 
### Proposed Solution (if any)

This is a minor papercut issue, but I think the fix should be relatively easy, with providing the input tag type properly.

**Comment by teocomi** [comment]
Good find, I hate websites that don't play nice with 1 password ;)
