### ISSUE TITLE
Add branch and stream name validation to schema directives

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#39]
[Schema directives](https://www.apollographql.com/blog/graphql-validation-using-directives-4908fd5c1055/) should have additional checks on the input names for branches and streams, if directives can't be used, validation will have to happen in the resolvers.
Below my suggested rules.

**Branches**
Currently implemented in the frontend:
- min length 3 (currently a branch with no name is allowed on the server!)
- max length 25

Optional rules to make branches URL and CLI friendly:
- only lowercase, numbers and dashes
- can't start with a dash `-`

**Streams**
Currently implemented in the frontend:
- min length 3 
- max length 25

**Comment by daviddekoning** [comment]
Is the stream name limit the stream ID or the user facing name? 25 characters seems quite small for the user facing name. I would suggest either no limit or something like 80 characters

**Comment by didimitrie** [comment]
streamids are generated by the server, so I suspect it's the user facing name. I'd also go for something more generous, as sometimes names get long in AEC. For reference, `Hello World How Are You Today?` is 32 chars. 

re branches:
> Optional rules to make branches URL and CLI friendly:
> only lowercase, numbers and dashes 

I would allow `/` too in names to be able to potentially group them nicely afterwards. We could handle this on the router end in the frontend (ie, `stream/{id}/branches/{branch_name_with_slash}` - we'd need to treat it as `stream/{id}/branches/*`)

**Comment by teocomi** [comment]
Alright, didn't realize 25 is so little! Yes, let's def go for something higher, 80-100 for a stream name should be enough?
Also agree on letting `/` in the branch names.

**Comment by daviddekoning** [comment]
If would be interesting to pull all the stream names from hestia to see what the length distribution is (do people rename streams much on hestia?) 

I'll get similar info from our servers, it will be an interesting point of reference.

**Comment by teocomi** [comment]
Good call! Yes we should do that ;)

**Comment by jenessaman** [comment]
Hey guys - we pulled stream names from our servers and took a quick look at the length distribution - check out the summary plots below:


![streamNameLength_cumPercentage](https://user-images.githubusercontent.com/69314485/96318145-2782ba80-0fdd-11eb-8afe-d993eb81b050.png)

![streamNameLength_boxWhisker jpg](https://user-images.githubusercontent.com/69314485/96318185-2a7dab00-0fdd-11eb-885a-e671cf447078.png)

![streamNameLength_summary](https://user-images.githubusercontent.com/69314485/96319258-7a5c7200-0fdd-11eb-8660-11afda36c1a6.png)

One thing to note on the longer Ireland names (>65 chars) - these names were styled as "<_analysis software_>_<_project name_>_<_model name_>_<_load case_>_<analysis iteration>", which seems like a pretty reasonable thing to expect from users.

**Comment by teocomi** [comment]
Wow super helpful, thanks @jenessaman ! We can cap it at 150, chars then to be safe. Worst that can happy it'll look weird in the frontend ;)
