### ISSUE TITLE
Viewer Embedding not working in incognito

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#399]
Embedded Viewers don't work when loaded from an incognito window. The issue seems to be still related to localStorage not being accessible:

```
DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

Sample: https://www.notion.so/speckle/Speckle-Viewer-Embedding-17419f4d9c7d447aa7d7de9e620d0233

**Comment by AlanRynne** [comment]
This was solved in #400
