### ISSUE TITLE
Frontend design work

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#40]
- [x] update user profile
- [x] update server info (if role permits)
- [ ] add subscriptions
- [ ] manage stream permissions
  - [ ] change link sharing
  - [x] add/remove collaborators
- [ ] create /revoke tokens
- [x] display more detailed commit info
- [x] delete streams & branches
- [x] pagination on streams & commits
- [x] tooltips
- [ ] (optional) create commits 
- [ ] (optional) proper home / feed page 
- [ ] (REQUIRED) Easter egg of sorts

**Comment by didimitrie** [comment]
Since this was marked as done in the alpha release, closing for now.
