### ISSUE TITLE
ObjectLoader: TextDecoder not supported in old browsers

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#407]
The TextDecoder class used at https://github.com/specklesystems/speckle-server/blob/22349df275f5f159201ac7e0643ba0a3677e1d27/packages/objectloader/index.js#L193 is not supported in older browsers and specifically affects the desktop Excel connector wich is many times tied to IE or old Edge versions.

We should look into alternatives, source: https://speckle.community/t/excel-referenceerror-textdecoder-is-not-defined/1696

**Comment by didimitrie** [comment]
I actually see there's a polyfill available that we could fallback on in older browsers: https://github.com/anonyco/FastestSmallestTextEncoderDecoder 

It's actually linked in [mdn](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder)) on the subject. This isn't an excuse though for micro$oft getting its act up tbh.

**Comment by gjedlicska** [comment]
after 3 different completely fresh windows installations i still cannot reproduce this issue.
