### ISSUE TITLE
is it possable to add support to maya & 3d max; 

### ISSUE THREAD

**Issue by asdMild** [specklesystems/speckle-server#413]
i was try to use the  speckle-server in game development, and the maya & 3d max is the two major DDC is always used with unreal engine.
and what more, is it possable to release a Binary server installer for local area network team(or a easier way to start a server, sorry, i was a newer for node.js, i start learn node.js when i contact speckle-server), the network to the remote server is too slow as our files is large than 500mb.

**Comment by didimitrie** [comment]
Hi @asdMild, i think this is more than one request issue wrapped in one! 

- connector requests for 3ds max and maya: best [shout on our forum!](https://speckle.community) - others from the community requested it. 
- server for local workflows: i think you'd best be served here by something that works purely with local transports, such as the grasshopper "send/receive local" nodes. They use a local sqlite db that can reside somewhere on a network drive. Again, if you have trouble running it locally, do poke on our [forum](https://speckle.community).

I'll close this for now, but please do post on the community forum the extra connector requests (this is not related to server). While we can't promise anything, it's worth seeing if others from the community would like direct integrations with maya or 3dsmax!
