### ISSUE TITLE
navigator chrome future issue

### ISSUE THREAD

**Issue by cristi8** [specklesystems/speckle-server#435]
Chrome reports that in a future version, information available on `navigator` will be reduced:

![frontend_chrome_issue](https://user-images.githubusercontent.com/2551138/137092545-4834a94a-3b1b-4ed8-93af-c4e399f6d56c.png)

**Comment by didimitrie** [comment]
can you tell us where in the source it's happening? if it's us and not a dependency, happy to try to resolve

**Comment by cristi8** [comment]
It doesn't provide all places where it's accessed.
I just noticed a new `Issues` thing in chrome (i think it's new).

Looking at the `Learn More` link, it mentions:

> If your site, service, library or application relies on certain bits of information being present in the User Agent string such as Chrome minor version, OS version number, or Android device model, you will need to begin the migration to use the User Agent Client Hints API instead.
> 
> If you don’t require any of these, then no changes are required and things should continue to operate as they have to date.
