### ISSUE TITLE
Prevent stream owners from revoking their own stream permissions

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#44]
A stream owner should not be allowed to revoke their own stream permissions in case they are the only owners of the stream, otherwise we could end up with orphaned streams.

**Comment by didimitrie** [comment]
Potential fix:

https://github.com/specklesystems/Server/blob/e4e583fee3b927aa2faa7a69327bb23d2239b154/modules/core/services/streams.js#L71-L72

should be 

```js
let [ { count } ] =  = Acl( ).count( { resourceId: streamId, role: 'stream:owner' } ) 
if( count === 1) { } etc. 
```

And, most importantly, this test needs to be corrected to exhibit the right behaviour: 

https://github.com/specklesystems/Server/blob/e4e583fee3b927aa2faa7a69327bb23d2239b154/modules/core/tests/streams.spec.js#L130-L137

**Comment by izzylys** [comment]
a follow up on this: orphan streams can indeed be created!

![stream-remove-owner-bug](https://user-images.githubusercontent.com/7717434/101917438-24acdc00-3bc0-11eb-8536-e68f93ffead9.gif)
