### ISSUE TITLE
Viewer: use displayStyle color for curves in the viewer

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-server#443]
### Expected vs. Actual Behavior

Curves are currently being rendered with the default grey color

### Proposed Solution (if any)
 Check for a `displayStyle` property and use the color if it exists. In the absence of `displayStyle`, check for `renderMaterial` and use diffuse value if it exists.

**Comment by didimitrie** [comment]
I remember seeing a threejs module helper - posting for posterity's sake only, maybe useful later: https://github.com/mrdoob/three.js/blob/master/examples/webgl_lines_fat.html

**Comment by AlexandruPopovici** [comment]
Cool, thanks! This is also using triangle primitives to render the lines. 
I've made a separate task regarding this issue [here](https://github.com/specklesystems/speckle-server/issues/722). I'll add it to the list of libraries/helpers there and we'll choose the most promising one out of them. If you know others, please feel free to add it to the list there.
