### ISSUE TITLE
Property Sets from IFCSpaces

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#454]
It seems like we're not correctly parsing psets for IFC Spaces, and possibly for other objects too. As [reported by Tim](https://speckle.community/t/finding-the-area-of-an-ifcspace/1954), that means important props are missing!

**Comment by timmcginley** [comment]
This probs overlaps a bit of the challenges we had in IFC JSON, The rigidity of the seperate property sets might be a bit weird nowadays but it still might help, especially if we can make it easier to access them.

I'm a bit old fashioned and my favourite way to view the total IFC is [IFC Analyzer](https://www.nist.gov/services-resources/software/ifc-file-analyzer) It shows you all the data in the IFC in a really nice way and seperates all the entities into different excel sheets. This might hold some clues for a future speckle IFC approach using branches for entities, much like you did in your HQ demo.

In terms of the IFC code, we might agree that we do not need to objectify the relationship between the entity and the property but where to put the values? There might be three main options to consider when you have identified all the properties:

1. to elevate all the props and quant single values to attributes of the entity. (you could just do the official props and no revit ones for instance) to avoid the duplicate area value.

2. to create a properties container and a quantities container as a child of the entity and dump the respective props and quants into there. This should probably also have a custom properties container too (you can't rely on these for interoperability) - but in your use case you might want to keep them?

3. make each property/quantityset a child of the entity. - This would keep the structure, enable you to potentially still push IFC later by rebuilding the relationship for the export whilst keeping the internal passing fast from GraphQL for instance?

Its a difficult call, but you will find the one that works best - how to do it so it is IFC, but is also easy to read / parse so the gymnastics on the QL to get the props are not too high.

Maybe this is a conversation to have over beer....
