### ISSUE TITLE
Frontend: Text in TextField of Project Globals can not be selected

### ISSUE THREAD

**Issue by iltabe** [specklesystems/speckle-server#463]
If it's your first time here - or you forgot about them - make sure you read the [contribution guidelines](CONTRIBUTING.md), and then feel free to delete this line! 

### Expected vs. Actual Behavior

Texts in global fields can not be selected
https://www.loom.com/share/2e11bbf032834ffe86fcfe6813c75ad3

### Reproduction Steps & System Config (win, osx, web, etc.)

I use firefox

### Proposed Solution (if any)

grabber point showed at the beginning of the line
![image](https://user-images.githubusercontent.com/64929000/140738351-581e6aa3-b8fa-4e5f-a032-ed5cf2a6d2fb.png)

**Comment by gjedlicska** [comment]
Yeah its wonky, also in other browsers, but FF is particularly weird.

As a workaround, if you click into the textbox, you can use the keyboard to select the text with `Ctrl+Shift+Arrow keys`

Thanks for reporting.
