### ISSUE TITLE
Stream `updatedAt` property not being set

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#47]
The stream `updatedAt` property is not being set correctly. 
It should update if:

- name or description change
- branches change
- new commits are pushed
- sharing changes
- ...

**Comment by didimitrie** [comment]
AFAIK, this was discussed in the standup some time ago, and we decided to: 
- keep the updatedAt on streams purely for stream name / description / etc - props that belong to the stream model
- display several other "updatedAt" fields in the UI, namely: 
  - last commit created at 
  - last branch created at 
  - etc. 

This is a temp lazy fix; as I believe we should be able to sort streams by the time they last had "activity" inside.

**Comment by teocomi** [comment]
Agreed, for clarity, the issue is referring to the fact that `updatedAt` is currently **never** updated on the stream. :)

**Comment by didimitrie** [comment]
> Agreed, for clarity, the issue is referring to the fact that `updatedAt` is currently **never** updated on the stream. :)

I think the following reaction is safe for consumption by the general public: L-O-L. Defs need to get on top of it!
