### ISSUE TITLE
Redirect on auth success

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#5]
### Behaviour
Frontend auth lock behaviour borkage on `localhost` bound redirects. 
- if the app is a web app, `window.location` redirect is the expected behaviour
- if the app is desktop bound (ie, connectors), the redirecting the browser to `window.location` is confusing (shows a blank page/404)

### Potential solution
Differentiate apps based on their nature. This might need modifying the current schema & needs propagation throughout the apps api.

**Comment by didimitrie** [comment]
Update: now this can be solved much more elegantly. Apps in the background have basically three plus 1 kinds of redirect urls:
- a relative one, ie `/explorer` - which means that we can safely do a `window.location` redirect. 
- a full url, ie `http://myapp.com/auth/redirect` - same as a above
- a custom scheme url, ie `speckle://auth/` - which means we should display a message on the lines of "you can now safely close this window"
- (the plus 1 case) a url called `self` for the main web app. Perhaps can be shortened to `/`. Again, safely redirect.

**Comment by daviddekoning** [comment]
I'm seeing a failure in the auth redirect in firefox, with the following error in the Console:

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/2060138/100017699-50028f00-2da9-11eb-8b34-3a930ab293b7.png)

it might be related to this? https://bugzilla.mozilla.org/show_bug.cgi?id=1528305

this is running the server at commit 18675bf551c6f771c1c9aa18972dc116f23fdb1f
