### ISSUE TITLE
`latest.speckle.dev/explorer` endpoint login redirects to `localhost:3000`

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-server#503]
Image is worth a thousand words 👇🏻 **Already fixed by @didimitrie by editing the db**, but should be looked into.

<img width="1369" alt="Screenshot 2021-12-16 at 10 45 52" src="https://user-images.githubusercontent.com/2316535/146349071-bd754c0f-1298-4e76-9a8d-5cb62d0810dc.png">

**Comment by didimitrie** [comment]
fixed quite some time ago
