### ISSUE TITLE
Viewer fails to load some 2.2.8-beta commits

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-server#505]
Upon loading, objects initially appear and seem to disappear when it focuses on the entire model https://latest.speckle.dev/streams/c544db35f5/commits/74ec351323

![2021-12-17 11 40 51](https://user-images.githubusercontent.com/2316535/146537010-e20283c4-6f66-43e3-9000-4edc5f1aea40.gif)

I think curves are disappearing bc they're getting a null renderMaterial such as this one https://latest.speckle.dev/streams/c544db35f5/objects/68871547f64b06363f55cd0e66b3b101
![image](https://user-images.githubusercontent.com/2316535/146536866-b61ead4a-e42c-4b87-8665-94c9a9ae197a.png)

on the other hand DirectShape's may be disappearing because of a null displayMesh or renderMaterial
![image](https://user-images.githubusercontent.com/2316535/146536882-503a2921-3de0-4dfd-9ce8-0ea4c876dc5c.png)

another good example is this commit https://latest.speckle.dev/streams/24c3741255/commits/1801290e7c. Loading each of the 6 objects works fine, but loading the commit does not... this time coming from Rhino

**Comment by cristi8** [comment]
First one is related to having most units set to `mm`, but some units missing, which default to `m` so when the camera zooms out to fit all objects, the `mm` ones are very very small.

The 2nd one looks like some object has a coordinate way bigger/smaller than the rest of the objects, so again looks like the viewer is zooming out too much to include all objects in the view.

I will leave the ticket open if we find any other viewer-related issues involving the new connector changes
