### ISSUE TITLE
Sample streams

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#54]
New users who sign up in the web app see only empty pages, it would be a great way to get them started if all new accounts had a couple of sample streams.
We have considered implementing this feature by:
- add a couple of sample streams to the server
- each time a user registers, clone the sample streams and share them

**Comment by didimitrie** [comment]
Closed for now - we link to an existing public stream on the xyz server. This is a half-solution, but solving this properly is a bit too tedious at the moment and there's no bandwidth.
