### ISSUE TITLE
Viewer: property explorer handle null values better

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#573]
Some string properties are incorrectly detected as objects and don't display, happened with `units` and room `name` so far:

![issue](https://user-images.githubusercontent.com/2679513/152529596-23101995-8a7a-4e41-ac55-bfd2eb79adf7.gif)

**Comment by didimitrie** [comment]
![image](https://user-images.githubusercontent.com/7696515/152530742-7e11e8f7-e259-49a5-8d38-027aaa764827.png)

the props are null - I'll edit this to be displayed better!
