### ISSUE TITLE
🌿 Branch updated mutation fires both branch updated and branch deleted subscriptions

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-server#60]
### Expected vs. Actual Behavior

The branch updated sub should be the only subscription that fires upon a branch update so that a user can handle it on its own. However, the branch deleted sub also fires after the branch updated sub. This is confusing and means a user can't handle the branch updated case effectively. All 3 (create/update/delete) cases have to be handled by fetching an updated branch list from the server because handling the updated / deleted cases separately would lead to unintended deletion of updated branches.

#### Optional: Affected Projects

None, but DesktopUI can change the way it is handling branch subscriptions if this is fixed.

**Comment by didimitrie** [comment]
https://user-images.githubusercontent.com/7696515/103037595-e971bc00-4574-11eb-9561-adec2702caff.mp4

I'm going to close this as i can't repro. Perhaps it's something to check for in Core!
