### ISSUE TITLE
Axe Busboy

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-server#602]
uploading an object fails from .net6 and it works from .net4.8

anything using dotnet core doesn't play nice with .net core stuff

**Comment by cristi8** [comment]
- [busboy] submitted detailed issue https://github.com/mscdex/busboy/issues/284
- [server] added better busboy error handling
- [.net] improved ServerTransport error handling
- [.net] surfaced `serverTransport.Api.CompressPayloads` field as a workaround for the busboy issue
- [.net] fixed integration tests
