### ISSUE TITLE
Viewer: Brep conversion only converts the first `displayValue` and assumes it's a mesh

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-server#613]
Brep conversion is hard coded to only take the first displayValue and assume it's a mesh. 
https://github.com/specklesystems/speckle-server/blob/f4a903922ebc2d6a4c8309c2e419565851c8e71b/packages/viewer/src/modules/converter/Converter.js#L278-L285

This is currently fine since all other Brep converters only output a single mesh.
But all other uses of  `displayValue` makes no assumptions about the type or number of elements.

So not a bug per-se, but an undocumented limitation/lack of robustness that might creep up on us in the future.

Q: Why do we need an explicit Brep conversion in the first place? There already is robust logic for `displayValue` fallback conversion.

**Comment by didimitrie** [comment]
Not a problem right now, breps are expected to have single display values (one hopes). Closing, as we discussed in our [last planning session](https://www.notion.so/speckle/Web-Team-Flip-Planning-0b6890eaf51146e89f9cee1056f76637).
