### ISSUE TITLE
FIlter Stream Activity with multiple action types

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#616]
As a developer, I'd like to filter a stream's activity with multiple action types. 
Making multiple queries and aggregating them could give different results if using a limit/cursor.

![image](https://user-images.githubusercontent.com/2679513/158031421-edfa1d21-ab66-41df-b930-294acad7458f.png)

**Comment by fabis94** [comment]
before we do this we'd also want to at the very least move activity stream filtering logic from the frontend to the backend, if not refactor this whole area entirely, cause currently we return activity stream items that aren't actually supposed to be shown anywhere - they're only inserted as an audit log essentially
