### ISSUE TITLE
💌 Send emails on behalf of users to invite new people to Speckle

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-server#62]
### Expected vs. Actual Behaviour

It would be fab to be able to send emails to people inviting them to easily create an account to the server. This would allow speckle user A to share a stream with non-speckle user B by providing B's email. From B's perspective, they should be directed to a signup flow and automatically added as a collaborator to the stream A wanted them to see.

#### Optional: Affected Projects

This would allow the DesktopUi and other connectors to share streams with people who don't have a speckle account yet.

**Comment by teocomi** [comment]
Was thinking about this today, we should let people invite coworkers also when:
- setting up the server for the first time
- creating an account
- creating / sharing a stream
