### ISSUE TITLE
Viewer: Colouring and displaying lines efficiently

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#623]
**What package are you referring to?**
Viewer

**Describe the bug**
Currently, any line-based geometry is treated as a second hand citizen in our viewer - it does not get merged into buffers, and filters and colors do not work with them. 

**Expected behavior**
The above to work. Reference discussion [here](https://speckle.community/t/assigning-colours-to-lines-curves-in-speckle-web-viewer/2490/3).

**Comment by clairekuang** [comment]
This is the same as: 
https://github.com/specklesystems/speckle-server/issues/443

**Comment by AlexandruPopovici** [comment]
The coloring issue got solved along with #443. For proper batching of lines I suggest we hold out until we start refactoring since the batching system will need to be properly thought out and it will completely change from what's currently implemented

**Comment by didimitrie** [comment]
@AlexandruPopovici, i guess this can be closed? If not, feel free to reopen - I'm trigger-happy cleanup mode right now :)
