### ISSUE TITLE
Favorite streams navbar redesign

### ISSUE THREAD

**Issue by fabis94** [specklesystems/speckle-server#657]

**Comment by fabis94** [comment]
@didimitrie I'm guessing you're going to start off by trying out some options, so let me know when you need my involvement

**Comment by didimitrie** [comment]
TBH, i'm just going to use the same design as `/admin`; that's been inspired by how gitlab does things with its navbar :D 

<img width="560" alt="image" src="https://user-images.githubusercontent.com/7696515/161710509-1cafa8ed-3028-44c4-9f17-68c6f6850072.png">
