### ISSUE TITLE
Viewer Materials: Fully metallic materials appear completely black in the viewer

### ISSUE THREAD

**Issue by JR-Morgan** [specklesystems/speckle-server#668]
### The Problem

Materials that have high metallic values appear completely black in the viewer.

See screenshot: (current 2.3.17-alpha.2678 viewer) - https://latest.speckle.dev/streams/2158263a8f/commits/3a629fc558
<img src="https://user-images.githubusercontent.com/45512892/161843194-f3fa76e8-830a-4e69-ab13-4137a0605a84.png" width=400 />

See initial bug report: https://speckle.community/t/speckle-2-4-0-connector-changes-enhanced-material-support/2442/9
### Expected behaviour

It is common for the metallic prop to have extreme values (1 or 0), and high metallicness normally doesn't affect base color much, like in Blender for example: 
<img src="https://user-images.githubusercontent.com/45512892/161842957-f9357706-d1fa-4770-b8df-60468ec30e62.png" width=400 />

### Suspicions/additional thoughts

There is a chance this has something to do with environment lighting / HDRI.
Since, in older versions of the viewer, we can see high metalness becomes light grey, not black

See screenshot: (old viewer ~09/2021, idk the version sorry)
<img src="https://user-images.githubusercontent.com/45512892/161842656-380d5c6f-6bbb-4983-88c9-b845ecfe7d72.png" width=400 />

**Comment by didimitrie** [comment]
closed in #777! 

<img width="458" alt="image" src="https://user-images.githubusercontent.com/7696515/171751376-f507bdc4-ce38-4a27-98a3-19987c6b4eed.png">
