### ISSUE TITLE
Terms of Service and Privacy Policy are not displayed correctly

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#669]
Because of the latest changes to protect us from xss attacks the Terms of Service and Privacy Policy are no longer displayed correctly:

![image](https://user-images.githubusercontent.com/2679513/161949413-d33a1435-e20b-4162-9816-8fdf98e3ac83.png)

I suggest we store each URL in a separate field, instead of doing this:

![image](https://user-images.githubusercontent.com/2679513/161949340-94f35aa6-fde3-4d9e-80bd-bf301af7bc31.png)

**Comment by didimitrie** [comment]
Note: temporarily fixed by reverting changes; we still need to implement this properly.

**Comment by didimitrie** [comment]
closing, as we discussed in our [last planning session](https://www.notion.so/speckle/Web-Team-Flip-Planning-0b6890eaf51146e89f9cee1056f76637).
