### ISSUE TITLE
Introduce proper workspaces support to get around duplicated dependencies in builds

### ISSUE THREAD

**Issue by fabis94** [specklesystems/speckle-server#689]
**What package are you referring to?**
This relates to the entire speckle-server repo. 

**Describe the bug**
Basically, when we do `npx lerna bootstrap` to symlink local packages as deps into eachother's node_modules, there's no de-duplication happening afterwards, that would clean up duplicate dependencies in symlinked package `node_modules` folders.

Because of this if we're not careful, it's easy to bundle duplicates of any dependencies that are dependencies of symlinked packages. So core-js, three.js - both of these libs are going to be bundled twice if you aren't careful.

**To Reproduce**
Add `import * as THREE from 'three'` anywhere, and you should get a warning in console about multiple three.js libs being loaded. This is because one version comes from 'viewer/node_modules/' and the other from 'frontend/node_modules'.

**Expected behavior**
After linking in packages, there should be appropriate de-duplication of dependencies. I've tried various things like upgrading webpack to 5 or using lerna boostrap with the --hoist flag, but none of these resolve the issue. The real solution is to move to a proper & configurable workspaces/monorepo solution like node 16+ workspaces or better yet `yarn` workspaces, because those are more configurable.

**Note: ** This doesn't affect speckle-server in production, because our CI/CD doesn't rely on symlinking to install local packages and the way it does the building & installing makes the deps be de-duplicated correctly.

**Comment by gjedlicska** [comment]
closed by #753

**Comment by fabis94** [comment]
awesome!
