### ISSUE TITLE
Remove CommitUpdate mutation and sub

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#69]
Commits should not be editble, we should then remove or disable the `CommitUpdate` mutation and subscription.

**Comment by didimitrie** [comment]
You can only edit the commit message, which i believe it's essential given that in some clients (dynamo, grasshopper) it's difficult to implement a proper way for the user to set it. 

I'm inclined to leave things as they are, unless we want to discuss more! (closing for now, but we can continue the convo here!)

**Comment by teocomi** [comment]
Ok fair enough!
