### ISSUE TITLE
Invite administration

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-server#709]
We've had many issues with email invites not making it to some users.

Add a simple admin page, that allows admins to invalidate / resend server invites.

**Comment by DuncanLithgow** [comment]
Does this need a whole admin page? Could we just say if someone tries to send an invite to an already invited address for a not activated account the form asks 

> This person has already been sent an invitation.
> Click below to remove their account and send a fresh invitation.

I feel like that would be enough to solve this immediate problem.

**Comment by didimitrie** [comment]
It puts us at a wee bit of spamming risk, and we want to resolve it properly - there's a bigger rethink going on re invite management! 

If it's really urgent, just DM me or @gjedlicska and we can sort it out if the invite is on one of our servers. If you control the deployment, the way we do it - wait for it - is manually deleting the invite from the db (it's in the `server_invites` table).
