### ISSUE TITLE
Select object in viewer when its data card (or nested card) is selected 

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-server#712]
**What package are you referring to?**
Viewer

**Is your feature request related to a problem? Please describe.**
It'll help users understand what object's properties they are browsing, and personally I keep expecting this behavior when debugging with the viewer

**Describe the solution you'd like**
Action: user selects data card in the data bar. If this card has a displayable object in the viewer, also highlight the object in the viewer. If not and there is a parent that does, select the parent.
May consider multiple selections if feasible.

**Comment by didimitrie** [comment]
finally implemented in #977!
