### ISSUE TITLE
Server: Cleanup & Update Dependencies 

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#72]
There's a wee bit of a dependency mess that causes problems at the moment: 
- Node: we're stuck at v12.X because of old knex version
- Old knex version is kept because: 
- Remote db connection needs to be figured out so as to allow upgrading `pg` to latest (`^7 > ^8`). There's some surmountable incompatibilities with our current DO's staging Postgresql db.

**Comment by gjedlicska** [comment]
This is not an issue since merging #73. There I bumped the pg version to ^8.

@didimitrie  this could be closed.
