### ISSUE TITLE
Running `npm run test` will wipe the local DB

### ISSUE THREAD

**Issue by cristi8** [specklesystems/speckle-server#731]
We shouldn't risk wiping the database when testing env is not correctly configured.

In my case, i have `.env` file, but not configured the `.env.test` file

CC @fabis94 : i am thinking either commit the `.env.test` in the repo, or fail the test if there is no such file. But running tests on the DB configured in .env should never happen. What do you think?

**Comment by fabis94** [comment]
@cristi8 I agree, review this fix - https://github.com/specklesystems/speckle-server/pull/734/files
