### ISSUE TITLE
objectloader package is missing its build

### ISSUE THREAD

**Issue by ericyoungberg** [specklesystems/speckle-server#749]
**What package are you referring to?**
objectloader

**Describe the bug**
Your package.json points to dist folder that doesn't exist in the published package.

**To Reproduce**

1. Go into a Node project
2. `yarn add @speckle/objectloader`
3. Navigate to _node_modules/@speckle/objectloader_
4. Notice that _dist/_ does not exist.

**Expected behavior**
I expect to be able to `yarn add @speckle/objectloader` without having to run build commands inside of my project's _node_modules_ folder.

**Comment by gjedlicska** [comment]
Thanks for the report @ericyoungberg, i was just working on a fix for this. Its out now, so both `@speckle/viewer` and `@speckle/objectloader` has the fix with the `latest` aka `2.5.5` version.
