### ISSUE TITLE
File upload time out and upload limits

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#750]
A few users are reporting getting a timeout or hitting file size limits using our file upload service with IFC files. It's a known limitation set to safeguard the service. We should look into adjusting or removing it as it's blocking adoption and usability.

**Comment by iainsproat** [comment]
As a first step, suggest that this should be configured per server deployment.  This would allow us to set larger limits on a case-by-case basis, especially enterprise deployments where the risk of a bad actor abusing large uploads is lower.
