### ISSUE TITLE
Deleted branches persist.

### ISSUE THREAD

**Issue by jsdbroughton** [specklesystems/speckle-server#755]
**What package are you referring to?**
This manifests itself both on the server and has visible artefacts in the viewer

**Describe the bug**
After a branch has been deleted, the ability to create a new branch with the same name (within an untested period of time)  is blocked. The deleted branch persists in the branch listing (for a time). Eventually, this resolves itself.

**To Reproduce**
Delete a branch, either in the frontend UI or via Client API. Shortly afterwards attempts to create a branch with the same name are blocked (unexpected), and so too is the ability to commit to the deleted branch (expected)

**Expected behaviour**
Either, a) branch is created, or b) documentation or error message clarifies that the action is eventual and not immediate.

**Screenshots**
![Screenshot 2022-05-15 at 14 17 38](https://user-images.githubusercontent.com/760691/168475322-0c816d0a-9605-465d-92ec-d2718cc0c30a.png)

UI artefact - the branch is visible in the listing (unexpected) but the query to retrieve it fails (expected). This mirrors the API call behaviour.

**Additional context**
This may be expected behaviour, the edge case of rapidly creating a deleted branch of the same name is not a frequent activity I assume. e.g. Deleting an email/id from Google, for instance, warns this may be a 24-hour wait for completion. Removing references to a branch in db may be similar.

**Comment by gjedlicska** [comment]
@didimitrie how were you able to repro this? I did not manage to do it on latest

**Comment by jsdbroughton** [comment]
I can extract minimal reproducible if it helps.

**Comment by didimitrie** [comment]
I reproduced... manually:

![image](https://user-images.githubusercontent.com/7696515/168791727-112884c1-efa2-4e02-92a9-be77c2055bf9.png)

Call it ~~fuzz~~ furious testing 😅

**Comment by gjedlicska** [comment]
Ok, i still cannot repro the branch remaining, but i ran into another, possibly related issue.

Steps:

* create branch
* delete branch ( it gets removed from the branch list for me ever time)
* create branch with the same name
* delete branch fails, thinks branch doesn't exist, while the gql api returns the undeletable branch. 

I'm thinking both of these could be an apollo / graphql cache thing.

![image](https://user-images.githubusercontent.com/57442769/168795176-d7ad5567-7947-44f4-8a42-485e8d7315bf.png)

**Comment by jsdbroughton** [comment]
It's intermittent behaviour feels like a race condition.

**Comment by fabis94** [comment]
I didn't manage to replicate the issue described in OP, but I was able to replicate Gergo's issue. I fixed that one and I think it should also fix the bug described in OP if it ever does happen.

If this still keeps happening then it would be beneficial to record a screen recording showing all of the page refreshes, navigations, all open tabs (or API clients) where the user is interacting with speckle-server, as all that matters and would be helpful when trying to figure out a hard to reproduce bug like this.

**Comment by jsdbroughton** [comment]
> If this still keeps happening then it would be beneficial to record a screen recording showing all of the page refreshes, navigations, all open tabs (or API clients) where the user is interacting with speckle-server, as all that matters and would be helpful when trying to figure out a hard to reproduce bug like this.

The manifestation as intermittently definitely *felt* like either caching or race condition so you may well have it sussed. I *might* try and replicate how I discovered it, or only report it if I happen to come across it again.
