### ISSUE TITLE
🎣 Inconsistent naming of speckle type property: `speckleType` vs `speckle_type`

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-server#78]
### Expected vs. Actual Behavior

All base object should have a property for their speckle type. This property should of course have a consistent name. At the moment, root base objects have a `speckleType` property while all child objects have a `speckle_type` property.

### Reproduction Steps & System Config (win, osx, web, etc.)

Upload a base object with nested children within it.

### Proposed Solution (if any)

Pick one of the names (prob `speckle_type`) and enforce it across all base objects.

**Comment by didimitrie** [comment]
as discussed with @izzylys, we're closing this one 😎
