### ISSUE TITLE
[Viewer] Block geometry meshes are displaying incorrectly

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-server#795]
**Describe the bug**
It seems that meshes within pretty simple block definitions are being parsed incorrectly in the viewer.

For context, I am working on improving blocks from SketchUp. These blocks have definition geometry lists starting with the `Mesh`(es), then any edges (`Line`s), then any nested `Block`s.

**To Reproduce**
Here's an example commit:
https://latest.speckle.dev/streams/0c6ad366c4/commits/cce248508a
![image](https://user-images.githubusercontent.com/7717434/172400358-6bf48ba3-728b-4c7e-8579-235444dc7d2a.png)

And this is what it looks like in SketchUp and Blender:
![image](https://user-images.githubusercontent.com/7717434/172399447-97d2af5d-629d-46bd-931c-008c780da3a2.png)

**Comment by didimitrie** [comment]
@AlexandruPopovici seems to have silently fixed this one :) 
![image](https://user-images.githubusercontent.com/7696515/173549621-faf46c53-2cb4-4175-971a-cbb18c097001.png)
