### ISSUE TITLE
Speckle Viewer is unpublished npm dependency of frontend

### ISSUE THREAD

**Issue by NGimbal** [specklesystems/speckle-server#81]
Thanks in advance for any and all help!

### Expected vs. Actual Behavior

In speckle-server/packages/frontend running:
`npm i `

throws error:
```
...
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@speckle%2fviewer - Not found
npm ERR! 404 
npm ERR! 404  '@speckle/viewer@^2.0.0' is not in the npm registry.
...
```

### Reproduction Steps & System Config (win, osx, web, etc.)
Pull repo, cd to speckle-server/packages/frontend and run npm i.

### Proposed Solution (if any)

So I got this working by the following steps:

1. remove @speckle/viewer from package.json
2. cd speckle-server/frontend
2. npm i
3. sudo npm link ../viewer

Don't know what the timeline for publishing the viewer on npm will be but this seems like a workable short term fix that could be documented?

**Comment by didimitrie** [comment]
Hey @NGimbal! Not sure re timeline either, but should happen soon. In the meantime, running `lerna bootstrap` should do the trick! 

I will add this to the docs.

**Comment by NGimbal** [comment]
Thanks so much!
