### ISSUE TITLE
Reworked server invites MVP

### ISSUE THREAD

**Issue by fabis94** [specklesystems/speckle-server#816]
Re-worked server & stream collaborator invites.
* Ability to resend, accept, decline invites, getting rid of auto-accept for stream collab invites
* A more intuitive workflow for when you're inviting a non-registered user to be a stream collaborator
* Possibility for user to remove himself from stream collabs
* Ability to see pending (server/stream) invites
* (If possible, cause least prio) Ability to request access to streams

**Comment by fabis94** [comment]
@didimitrie I've re-checked the main workflows and the issues you originally reported and things seem to work fine now, so we can probably merge this

**Comment by didimitrie** [comment]
Yep, happy to do so!
