### ISSUE TITLE
Close all Critical & High priority alerts

### ISSUE THREAD

**Issue by iainsproat** [specklesystems/speckle-server#846]
https://github.com/specklesystems/speckle-server/security/dependabot

**Comment by devarsh10** [comment]
I want to close these alerts and want to work on this issue. Please assign me this issue if it is not solved yet.
Regards.

**Comment by iainsproat** [comment]
Hi @devarsh10 , thank you for your interest in Speckle. Unfortunately this is not a good first issue to work on.  Please feel free to try to attempt something else in the backlog if you wish, or from the backlogs from our other repositories.  Something interesting to try would be to create a Speckle Connector for a software package of your choice.
Some reference material to help you understand more about Speckle can be found here: https://speckle.guide/dev/

**Comment by devarsh10** [comment]
Okay. Thank You for replying.
