### ISSUE TITLE
Reusable server email templating 

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-server#853]
Create a maintainable solution to work with email templates on the server.

The current string literals solution is messy and hard to maintain.
The new solution should give us an easy to use functionality, that provides a consistent look and feel for multiple mail contents.

**Comment by fabis94** [comment]
Part 1 done, created a template using MJML - a markup language created to simplify EMail HTML creation: https://github.com/specklesystems/speckle-email-templates/blob/main/dist/main_server_template.html

The next part is to actually integrate this into speckle-server

**Comment by fabis94** [comment]
PR: https://discord.com/channels/726756379083145269/960898733988528208/1006490168074715167
