### ISSUE TITLE
error while starting 2.0 server

### ISSUE THREAD

**Issue by riteshonx** [specklesystems/speckle-server#86]
Here I am getting following error when I start the server, though my postgres and redis is running. Can you help ?

C:\ONX\Speckle\speckle-server-master\packages\server>npm run dev

> @speckle/server@2.1.0 dev C:\ONX\Speckle\speckle-server-master\packages\server
> cross-env NODE_ENV=development DEBUG=speckle:* nodemon ./bin/www --watch . --watch ./bin/www  -e js,graphql,env

[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.* bin\www
[nodemon] watching extensions: js,graphql,env
[nodemon] starting `node ./bin/www`
  speckle:db-startup Loaded knex conf for development +0ms
  speckle:www KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
  speckle:www     at Client_PG.acquireConnection (C:\ONX\Speckle\speckle-server-master\packages\server\node_modules\knex\lib\client.js:348:26)
  speckle:www     at async listCompleted (C:\ONX\Speckle\speckle-server-master\packages\server\node_modules\knex\lib\migrate\migration-list-resolver.js:12:3)
  speckle:www     at async Promise.all (index 1)
  speckle:www     at async Migrator.latest (C:\ONX\Speckle\speckle-server-master\packages\server\node_modules\knex\lib\migrate\Migrator.js:64:29)
  speckle:www     at async exports.init (C:\ONX\Speckle\speckle-server-master\packages\server\app.js:38:3) +0ms

**Comment by didimitrie** [comment]
Hey @riteshonx, it's probably the node version - which one are you using? Otherwise, please give it a shot with node v12! If you've installed it with nvm should be easy to switch between them.

**Comment by riteshonx** [comment]
I have tried with v12, but still getting error. Can you suggest where I need to add password in .env file.
speckle:db-startup Loaded knex conf for development +0ms
  speckle:www error: password authentication failed for user "Ritesh"
  speckle:www     at Connection.parseE (C:\ONX\Speckle\speckle-server-master\packages\server\node_modules\pg\lib\connecti

**Comment by gjedlicska** [comment]
Currently you have to provide a connection uri as the `POSTGRES_URL` in a format like `postgres://{database_user}:{database_password}@{database_adress}/{database_name}`. Replace the parts in curly-s, including the curlys. This should get you to connect to a postgres instance. 

Make sure the database user has table create rights, so that the necessary tables can be created by the server migration scripts.

**Comment by riteshonx** [comment]
I have added in format you shared, but still getting following error.

speckle:www Error: getaddrinfo ENOTFOUND postgres

**Comment by riteshonx** [comment]
POSTGRES_URL="postgres://username:password@127.0.0.1:5432//riteshdb"

**Comment by riteshonx** [comment]
my pgadmin url adress is "http://127.0.0.1:50172/browser/"

**Comment by gjedlicska** [comment]
You have double '/'es before the database name. Try with just a single slash.

**Comment by riteshonx** [comment]
tried with POSTGRES_URL="postgres://username:password@127.0.0.1:5432/riteshdb" but still same error

**Comment by riteshonx** [comment]
hi I am able to solve the issue and server is running 
Thank you for help.

**Comment by riteshonx** [comment]
but getting following error in frontend app

> @speckle/frontend@2.1.0 serve C:\ONX\Speckle\speckle-server-master\packages\frontend
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                       3:35:49 PM

This dependency was not found:

* @speckle/viewer in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Renderer.vue?vue&type=script&lang=js&

**Comment by gjedlicska** [comment]
You have to build the viewer package first and initialize the monorepo dependency linking via `$ lerna init`.

An alternative method is to run the whole server via docker and docker-compose. Check out the root readme for instructions.
