### ISSUE TITLE
Enhancement: Viewer - Section Box

### ISSUE THREAD

**Issue by NGimbal** [specklesystems/speckle-server#89]
Implement a section box as seen in this demo:
[Demo](http://daign.github.io/clipping-with-caps/)

Interaction should follow this pattern (repo for demo above):
[Clipping With Caps](https://github.com/daign/clipping-with-caps)

[Another useful demo](https://threejs.org/examples/?q=clipping#webgl_clipping_stencil)

Steps to implement (approximate):
- [x] Implement SectionBox class that displays geometry, add to Viewer scene
- [x] Implement face picking & hover state using SelectionHelper.js ideally
- [x] Implement dragging interaction
- [x] Align clip planes with box faces
- [x] Apply clip planes to materials
- [x] Limit planes so they can't cross each other while draggin
- [x] Set from bounding box
- [x] Translate, ~Rotate~ (not going to get into ui for this yet)
- [ ] ~Stencils~

I'm actively working on this :) please let me know if you have any thoughts or advice as to how this should work / be implemented.

**Comment by didimitrie** [comment]
Thanks @NGimbal! I'm quite excited to see this happening!
