### ISSUE TITLE
Viewer should inform the user when there are no visible elements

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#91]
Small enhancement suggestion: the viewer should inform the user when there are no visible elements in a commit, or maybe the viewer could be disabled alltogether.

**Comment by teocomi** [comment]
Maybe points should be considered as visible elements?

![image](https://user-images.githubusercontent.com/2679513/114425209-c1a07580-9bb0-11eb-8e72-50fcc817d657.png)

**Comment by didimitrie** [comment]
Yes. The current implementation is buggy - it doesn't work for gh based streams (or, I guess, dynamo ones?). I need to do more testing and fix it.
