### ISSUE TITLE
Invalid/expired tokens should throw before the resolver is hit

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-server#927]
Currently, we just suppress the error and only attach it to ctx:

https://github.com/specklesystems/speckle-server/blob/8ecc7f5a68301f65970c99618566a79c33d22eb2/packages/server/modules/shared/index.js#L86

See internal discussion: https://discord.com/channels/726756379083145269/743146087618969652/1008695518253301821

**Comment by fabis94** [comment]
Passing the torch to @gjedlicska, cause the same context builder is used for our REST endpoints as well, and those need some changes to support throwing in the context builder.

Here's the PR so far: https://github.com/specklesystems/speckle-server/pull/944/files

The remaining issues are:
* The REST middleware logic should be updated to take into account that the context builder function can throw errors now and kill the request before any other middleware checks are done
* We'd want the context object to be initialized for all REST endpoints, similarly how its invoked for all GQL operations, so it would be great if it could be invoked globally and would be unskippable
* Ditto for error handling - currently if you forget to do error handling in your Express handler, the error will bubble out and kill the request in the default ugly way - with a 500 status code and an ugly HTML page. We should add a global error handler that at the very least outputs the error message in a JSON format.

We also discussed a tangential issue - not having a standard way to resolve what the status code & error message should be for any errors thrown in the system. We discussed how it would be nice to have a standard process that checks the properties on the error object (those could be defined on BaseError) and decides how to output them to the response.

For info on how error handling is usually managed in the backend for GQL APIs see this: https://www.apollographql.com/docs/apollo-server/data/errors#custom-errors

Also you'll find that we already have some code that deals with formatting errors for GQL output: `modules/core/graph/setup.js:buildErrorFormatter()`

We also have this apollo plugin for sending stuff to sentry: `logging/apolloPlugin.js`
