### ISSUE TITLE
Add circleci pre-commit hook

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-server#949]
With the circleci cli it is possible to validate the local config. Lets add a pre-commit hook, to check the config validity. Saves a lot of time...

https://github.com/CircleCI-Public/circleci-cli

**Comment by iainsproat** [comment]
Ah, I'd added it to the pre-commit runner image but not speckle-server! https://github.com/specklesystems/pre-commit-runner-image/blob/2ce36c28aed92e72a234e02d1300f2b0796504b8/.pre-commit-config.yaml#L27
Will add it here too 👍
