### ISSUE TITLE
Server static assets

### ISSUE THREAD

**Issue by gjedlicska** [specklesystems/speckle-server#957]
add possibility to serve static assets from the server stack

considerations:
- [x] be able to use it in development
- [x] have proper caching in production

**Comment by gjedlicska** [comment]
partly solved in #979, needs nginx cache

**Comment by fabis94** [comment]
@gjedlicska 
1. What are the remaining steps here?
2. Could you type out a short explanation of how devs should be using this? E.g. if you put file in folder X, it's going to be accessible at url Y

**Comment by gjedlicska** [comment]
Files go into the `server/assets/public` folder and they are served in the `CANNONICAL_URL/static/${fileName}` url.

Its not ready for prod tough since, the frontend nginx config is not properly proxying the requests to the backend.

**Comment by gjedlicska** [comment]
fixed in #1030
