### ISSUE TITLE
Permissions on rest endpoints

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#96]
Permissions are currently enforced a bit brutally on the rest endpoints for streaming objects; i.e. public stream with link sharing on can't be viewed in the 3d viewer, even if logged in. 

I suspect that this might be the case as well in grasshopper/dynamo too 😬

Fix: check permissions on the stream same as the gql endpoints do.

**Comment by AlanRynne** [comment]
Reopening as Cristian is having this issue again!

**Comment by didimitrie** [comment]
it was a pebkac on my end on the staging server - it's actually resolved
