### ISSUE TITLE
Multi select commit actions in the frontend

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#984]
Currently, there is no efficient way of editing or deleting multiple commits at the same time: you need to load the commit (potentially heavy operation, given the fact that it loads the 3D model), and then hit the edit button, and then you can finally delete it, etc. 

We should allow for easier bulk operations to happen, specifically `delete` and `move to another branch`. 

Proposal: commit cards on a branch page have a small extra checkbox that can be used to select them. Once a commit or more is selected, a top action bar appears that allows for either deleting the respective commits or moving them to another branch. 

Quick mock: 
![Multiedit](https://user-images.githubusercontent.com/7696515/188405486-9990880e-dd4f-4ef9-ba41-a190446491ea.png)

Note the info on permissions. Styling TBD :D

**Comment by fabis94** [comment]
@didimitrie Everything makes sense except the indeterminate checkbox part, IMO it doesn't make sense semantically. Indeterminate usually means that it's partially checked in, but if the checkbox is greyed out and the user can't even check it, it doesn't make sense showing it as "partially checked".

**Comment by didimitrie** [comment]
Yeah, also not happy with it. Anything you see better can go in (empty disabled?), as long as we can display a tooltip communicating the "only authors etc" part.
