### ISSUE TITLE
IFC: Importer incorrectly parses filenames with multiple `.` characters

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-server#985]
## What package are you referring to?

IFC Service

## Describe the bug

Reported in the forum

## To Reproduce

Attempt to import a file with multiple `.` chars in its name, i.e. `myfilename.2.ifc`

Reported on the forum, see gif there: https://speckle.community/t/file-importing-extension/3530

## Expected behavior

Filename should be fully parsed with `.` included until the last one.

## Screenshots

![image](https://user-images.githubusercontent.com/2316535/188470510-69697c4d-a056-43a1-bff9-ff3833695a06.png)

**Comment by maks2199** [comment]
How are you doing with this issue?

**Comment by gjedlicska** [comment]
hey @maks2199, sorry for the late reply. The issue if getting a fix in #1031. It should land on all release channels soon™
