### ISSUE TITLE
Viewer Redux Bugs Bucket List

### ISSUE THREAD

**Issue by didimitrie** [specklesystems/speckle-server#988]
Bucket list issue for tracking new viewer beta bugs: 
- [x] #987 
- [x] #989
- [x] #990
- [x] #991
- [x] #992
- [x] #995 
- [x] #996 
- [x] #1012

**Comment by gjedlicska** [comment]
![image](https://user-images.githubusercontent.com/57442769/189122444-9a05ac88-32d6-44c7-934d-fc50ff379c1b.png)

Loader bar remains visible even after successful dataload.

Link:
https://latest.speckle.dev/streams/7d051a6449/commits/810f4e1bec?filter=%7B%7D&c=%5B-354.24692,-150.43859,426.46375,-2.65829,20.40531,10.15873,0,1%5D

Os: Firefox Linux
Repro: I just opened the link
